// Code generated by ent, DO NOT EDIT.

package articlepurchase

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the articlepurchase type in the database.
	Label = "article_purchase"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldArticleID holds the string denoting the article_id field in the database.
	FieldArticleID = "article_id"
	// FieldBlockID holds the string denoting the block_id field in the database.
	FieldBlockID = "block_id"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldPurchasedAt holds the string denoting the purchased_at field in the database.
	FieldPurchasedAt = "purchased_at"
	// Table holds the table name of the articlepurchase in the database.
	Table = "article_purchases"
)

// Columns holds all SQL columns for articlepurchase fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldArticleID,
	FieldBlockID,
	FieldPrice,
	FieldOrderNo,
	FieldPurchasedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// BlockIDValidator is a validator for the "block_id" field. It is called by the builders before save.
	BlockIDValidator func(string) error
	// PriceValidator is a validator for the "price" field. It is called by the builders before save.
	PriceValidator func(int) error
	// DefaultPurchasedAt holds the default value on creation for the "purchased_at" field.
	DefaultPurchasedAt func() time.Time
)

// OrderOption defines the ordering options for the ArticlePurchase queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByArticleID orders the results by the article_id field.
func ByArticleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArticleID, opts...).ToFunc()
}

// ByBlockID orders the results by the block_id field.
func ByBlockID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockID, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByPurchasedAt orders the results by the purchased_at field.
func ByPurchasedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchasedAt, opts...).ToFunc()
}
