// Code generated by ent, DO NOT EDIT.

package articlepurchase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldUserID, v))
}

// ArticleID applies equality check predicate on the "article_id" field. It's identical to ArticleIDEQ.
func ArticleID(v uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldArticleID, v))
}

// BlockID applies equality check predicate on the "block_id" field. It's identical to BlockIDEQ.
func BlockID(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldBlockID, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v int) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldPrice, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldOrderNo, v))
}

// PurchasedAt applies equality check predicate on the "purchased_at" field. It's identical to PurchasedAtEQ.
func PurchasedAt(v time.Time) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldPurchasedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldContainsFold(FieldUserID, v))
}

// ArticleIDEQ applies the EQ predicate on the "article_id" field.
func ArticleIDEQ(v uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldArticleID, v))
}

// ArticleIDNEQ applies the NEQ predicate on the "article_id" field.
func ArticleIDNEQ(v uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNEQ(FieldArticleID, v))
}

// ArticleIDIn applies the In predicate on the "article_id" field.
func ArticleIDIn(vs ...uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldIn(FieldArticleID, vs...))
}

// ArticleIDNotIn applies the NotIn predicate on the "article_id" field.
func ArticleIDNotIn(vs ...uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNotIn(FieldArticleID, vs...))
}

// ArticleIDGT applies the GT predicate on the "article_id" field.
func ArticleIDGT(v uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGT(FieldArticleID, v))
}

// ArticleIDGTE applies the GTE predicate on the "article_id" field.
func ArticleIDGTE(v uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGTE(FieldArticleID, v))
}

// ArticleIDLT applies the LT predicate on the "article_id" field.
func ArticleIDLT(v uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLT(FieldArticleID, v))
}

// ArticleIDLTE applies the LTE predicate on the "article_id" field.
func ArticleIDLTE(v uint) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLTE(FieldArticleID, v))
}

// BlockIDEQ applies the EQ predicate on the "block_id" field.
func BlockIDEQ(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldBlockID, v))
}

// BlockIDNEQ applies the NEQ predicate on the "block_id" field.
func BlockIDNEQ(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNEQ(FieldBlockID, v))
}

// BlockIDIn applies the In predicate on the "block_id" field.
func BlockIDIn(vs ...string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldIn(FieldBlockID, vs...))
}

// BlockIDNotIn applies the NotIn predicate on the "block_id" field.
func BlockIDNotIn(vs ...string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNotIn(FieldBlockID, vs...))
}

// BlockIDGT applies the GT predicate on the "block_id" field.
func BlockIDGT(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGT(FieldBlockID, v))
}

// BlockIDGTE applies the GTE predicate on the "block_id" field.
func BlockIDGTE(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGTE(FieldBlockID, v))
}

// BlockIDLT applies the LT predicate on the "block_id" field.
func BlockIDLT(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLT(FieldBlockID, v))
}

// BlockIDLTE applies the LTE predicate on the "block_id" field.
func BlockIDLTE(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLTE(FieldBlockID, v))
}

// BlockIDContains applies the Contains predicate on the "block_id" field.
func BlockIDContains(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldContains(FieldBlockID, v))
}

// BlockIDHasPrefix applies the HasPrefix predicate on the "block_id" field.
func BlockIDHasPrefix(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldHasPrefix(FieldBlockID, v))
}

// BlockIDHasSuffix applies the HasSuffix predicate on the "block_id" field.
func BlockIDHasSuffix(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldHasSuffix(FieldBlockID, v))
}

// BlockIDEqualFold applies the EqualFold predicate on the "block_id" field.
func BlockIDEqualFold(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEqualFold(FieldBlockID, v))
}

// BlockIDContainsFold applies the ContainsFold predicate on the "block_id" field.
func BlockIDContainsFold(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldContainsFold(FieldBlockID, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v int) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v int) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...int) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...int) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v int) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v int) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v int) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v int) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLTE(FieldPrice, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoIsNil applies the IsNil predicate on the "order_no" field.
func OrderNoIsNil() predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldIsNull(FieldOrderNo))
}

// OrderNoNotNil applies the NotNil predicate on the "order_no" field.
func OrderNoNotNil() predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNotNull(FieldOrderNo))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldContainsFold(FieldOrderNo, v))
}

// PurchasedAtEQ applies the EQ predicate on the "purchased_at" field.
func PurchasedAtEQ(v time.Time) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldEQ(FieldPurchasedAt, v))
}

// PurchasedAtNEQ applies the NEQ predicate on the "purchased_at" field.
func PurchasedAtNEQ(v time.Time) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNEQ(FieldPurchasedAt, v))
}

// PurchasedAtIn applies the In predicate on the "purchased_at" field.
func PurchasedAtIn(vs ...time.Time) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldIn(FieldPurchasedAt, vs...))
}

// PurchasedAtNotIn applies the NotIn predicate on the "purchased_at" field.
func PurchasedAtNotIn(vs ...time.Time) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldNotIn(FieldPurchasedAt, vs...))
}

// PurchasedAtGT applies the GT predicate on the "purchased_at" field.
func PurchasedAtGT(v time.Time) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGT(FieldPurchasedAt, v))
}

// PurchasedAtGTE applies the GTE predicate on the "purchased_at" field.
func PurchasedAtGTE(v time.Time) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldGTE(FieldPurchasedAt, v))
}

// PurchasedAtLT applies the LT predicate on the "purchased_at" field.
func PurchasedAtLT(v time.Time) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLT(FieldPurchasedAt, v))
}

// PurchasedAtLTE applies the LTE predicate on the "purchased_at" field.
func PurchasedAtLTE(v time.Time) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.FieldLTE(FieldPurchasedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ArticlePurchase) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ArticlePurchase) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ArticlePurchase) predicate.ArticlePurchase {
	return predicate.ArticlePurchase(sql.NotPredicates(p))
}
