// Code generated by ent, DO NOT EDIT.

package resourceorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the resourceorder type in the database.
	Label = "resource_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldResourceItemID holds the string denoting the resource_item_id field in the database.
	FieldResourceItemID = "resource_item_id"
	// FieldBusinessOrderNo holds the string denoting the business_order_no field in the database.
	FieldBusinessOrderNo = "business_order_no"
	// FieldExternalOrderNo holds the string denoting the external_order_no field in the database.
	FieldExternalOrderNo = "external_order_no"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSnapshot holds the string denoting the snapshot field in the database.
	FieldSnapshot = "snapshot"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// EdgeResource holds the string denoting the resource edge name in mutations.
	EdgeResource = "resource"
	// EdgeResourceItem holds the string denoting the resource_item edge name in mutations.
	EdgeResourceItem = "resource_item"
	// Table holds the table name of the resourceorder in the database.
	Table = "resource_orders"
	// ResourceTable is the table that holds the resource relation/edge.
	ResourceTable = "resource_orders"
	// ResourceInverseTable is the table name for the Resource entity.
	// It exists in this package in order to avoid circular dependency with the "resource" package.
	ResourceInverseTable = "resources"
	// ResourceColumn is the table column denoting the resource relation/edge.
	ResourceColumn = "resource_id"
	// ResourceItemTable is the table that holds the resource_item relation/edge.
	ResourceItemTable = "resource_orders"
	// ResourceItemInverseTable is the table name for the ResourceItem entity.
	// It exists in this package in order to avoid circular dependency with the "resourceitem" package.
	ResourceItemInverseTable = "resource_items"
	// ResourceItemColumn is the table column denoting the resource_item relation/edge.
	ResourceItemColumn = "resource_item_id"
)

// Columns holds all SQL columns for resourceorder fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldResourceID,
	FieldResourceItemID,
	FieldBusinessOrderNo,
	FieldExternalOrderNo,
	FieldAmount,
	FieldStatus,
	FieldSnapshot,
	FieldPaidAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// BusinessOrderNoValidator is a validator for the "business_order_no" field. It is called by the builders before save.
	BusinessOrderNoValidator func(string) error
	// ExternalOrderNoValidator is a validator for the "external_order_no" field. It is called by the builders before save.
	ExternalOrderNoValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the ResourceOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByResourceItemID orders the results by the resource_item_id field.
func ByResourceItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceItemID, opts...).ToFunc()
}

// ByBusinessOrderNo orders the results by the business_order_no field.
func ByBusinessOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessOrderNo, opts...).ToFunc()
}

// ByExternalOrderNo orders the results by the external_order_no field.
func ByExternalOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalOrderNo, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByResourceField orders the results by resource field.
func ByResourceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResourceStep(), sql.OrderByField(field, opts...))
	}
}

// ByResourceItemField orders the results by resource_item field.
func ByResourceItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResourceItemStep(), sql.OrderByField(field, opts...))
	}
}
func newResourceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResourceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ResourceTable, ResourceColumn),
	)
}
func newResourceItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResourceItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ResourceItemTable, ResourceItemColumn),
	)
}
