// Code generated by ent, DO NOT EDIT.

package resourceorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldUserID, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldResourceID, v))
}

// ResourceItemID applies equality check predicate on the "resource_item_id" field. It's identical to ResourceItemIDEQ.
func ResourceItemID(v uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldResourceItemID, v))
}

// BusinessOrderNo applies equality check predicate on the "business_order_no" field. It's identical to BusinessOrderNoEQ.
func BusinessOrderNo(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldBusinessOrderNo, v))
}

// ExternalOrderNo applies equality check predicate on the "external_order_no" field. It's identical to ExternalOrderNoEQ.
func ExternalOrderNo(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldExternalOrderNo, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldStatus, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldPaidAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLTE(FieldUserID, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceItemIDEQ applies the EQ predicate on the "resource_item_id" field.
func ResourceItemIDEQ(v uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldResourceItemID, v))
}

// ResourceItemIDNEQ applies the NEQ predicate on the "resource_item_id" field.
func ResourceItemIDNEQ(v uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldResourceItemID, v))
}

// ResourceItemIDIn applies the In predicate on the "resource_item_id" field.
func ResourceItemIDIn(vs ...uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldResourceItemID, vs...))
}

// ResourceItemIDNotIn applies the NotIn predicate on the "resource_item_id" field.
func ResourceItemIDNotIn(vs ...uint) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldResourceItemID, vs...))
}

// ResourceItemIDIsNil applies the IsNil predicate on the "resource_item_id" field.
func ResourceItemIDIsNil() predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIsNull(FieldResourceItemID))
}

// ResourceItemIDNotNil applies the NotNil predicate on the "resource_item_id" field.
func ResourceItemIDNotNil() predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotNull(FieldResourceItemID))
}

// BusinessOrderNoEQ applies the EQ predicate on the "business_order_no" field.
func BusinessOrderNoEQ(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldBusinessOrderNo, v))
}

// BusinessOrderNoNEQ applies the NEQ predicate on the "business_order_no" field.
func BusinessOrderNoNEQ(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldBusinessOrderNo, v))
}

// BusinessOrderNoIn applies the In predicate on the "business_order_no" field.
func BusinessOrderNoIn(vs ...string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldBusinessOrderNo, vs...))
}

// BusinessOrderNoNotIn applies the NotIn predicate on the "business_order_no" field.
func BusinessOrderNoNotIn(vs ...string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldBusinessOrderNo, vs...))
}

// BusinessOrderNoGT applies the GT predicate on the "business_order_no" field.
func BusinessOrderNoGT(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGT(FieldBusinessOrderNo, v))
}

// BusinessOrderNoGTE applies the GTE predicate on the "business_order_no" field.
func BusinessOrderNoGTE(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGTE(FieldBusinessOrderNo, v))
}

// BusinessOrderNoLT applies the LT predicate on the "business_order_no" field.
func BusinessOrderNoLT(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLT(FieldBusinessOrderNo, v))
}

// BusinessOrderNoLTE applies the LTE predicate on the "business_order_no" field.
func BusinessOrderNoLTE(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLTE(FieldBusinessOrderNo, v))
}

// BusinessOrderNoContains applies the Contains predicate on the "business_order_no" field.
func BusinessOrderNoContains(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldContains(FieldBusinessOrderNo, v))
}

// BusinessOrderNoHasPrefix applies the HasPrefix predicate on the "business_order_no" field.
func BusinessOrderNoHasPrefix(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldHasPrefix(FieldBusinessOrderNo, v))
}

// BusinessOrderNoHasSuffix applies the HasSuffix predicate on the "business_order_no" field.
func BusinessOrderNoHasSuffix(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldHasSuffix(FieldBusinessOrderNo, v))
}

// BusinessOrderNoEqualFold applies the EqualFold predicate on the "business_order_no" field.
func BusinessOrderNoEqualFold(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEqualFold(FieldBusinessOrderNo, v))
}

// BusinessOrderNoContainsFold applies the ContainsFold predicate on the "business_order_no" field.
func BusinessOrderNoContainsFold(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldContainsFold(FieldBusinessOrderNo, v))
}

// ExternalOrderNoEQ applies the EQ predicate on the "external_order_no" field.
func ExternalOrderNoEQ(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldExternalOrderNo, v))
}

// ExternalOrderNoNEQ applies the NEQ predicate on the "external_order_no" field.
func ExternalOrderNoNEQ(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldExternalOrderNo, v))
}

// ExternalOrderNoIn applies the In predicate on the "external_order_no" field.
func ExternalOrderNoIn(vs ...string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldExternalOrderNo, vs...))
}

// ExternalOrderNoNotIn applies the NotIn predicate on the "external_order_no" field.
func ExternalOrderNoNotIn(vs ...string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldExternalOrderNo, vs...))
}

// ExternalOrderNoGT applies the GT predicate on the "external_order_no" field.
func ExternalOrderNoGT(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGT(FieldExternalOrderNo, v))
}

// ExternalOrderNoGTE applies the GTE predicate on the "external_order_no" field.
func ExternalOrderNoGTE(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGTE(FieldExternalOrderNo, v))
}

// ExternalOrderNoLT applies the LT predicate on the "external_order_no" field.
func ExternalOrderNoLT(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLT(FieldExternalOrderNo, v))
}

// ExternalOrderNoLTE applies the LTE predicate on the "external_order_no" field.
func ExternalOrderNoLTE(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLTE(FieldExternalOrderNo, v))
}

// ExternalOrderNoContains applies the Contains predicate on the "external_order_no" field.
func ExternalOrderNoContains(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldContains(FieldExternalOrderNo, v))
}

// ExternalOrderNoHasPrefix applies the HasPrefix predicate on the "external_order_no" field.
func ExternalOrderNoHasPrefix(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldHasPrefix(FieldExternalOrderNo, v))
}

// ExternalOrderNoHasSuffix applies the HasSuffix predicate on the "external_order_no" field.
func ExternalOrderNoHasSuffix(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldHasSuffix(FieldExternalOrderNo, v))
}

// ExternalOrderNoIsNil applies the IsNil predicate on the "external_order_no" field.
func ExternalOrderNoIsNil() predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIsNull(FieldExternalOrderNo))
}

// ExternalOrderNoNotNil applies the NotNil predicate on the "external_order_no" field.
func ExternalOrderNoNotNil() predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotNull(FieldExternalOrderNo))
}

// ExternalOrderNoEqualFold applies the EqualFold predicate on the "external_order_no" field.
func ExternalOrderNoEqualFold(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEqualFold(FieldExternalOrderNo, v))
}

// ExternalOrderNoContainsFold applies the ContainsFold predicate on the "external_order_no" field.
func ExternalOrderNoContainsFold(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldContainsFold(FieldExternalOrderNo, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldContainsFold(FieldStatus, v))
}

// SnapshotIsNil applies the IsNil predicate on the "snapshot" field.
func SnapshotIsNil() predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIsNull(FieldSnapshot))
}

// SnapshotNotNil applies the NotNil predicate on the "snapshot" field.
func SnapshotNotNil() predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotNull(FieldSnapshot))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.FieldNotNull(FieldPaidAt))
}

// HasResource applies the HasEdge predicate on the "resource" edge.
func HasResource() predicate.ResourceOrder {
	return predicate.ResourceOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ResourceTable, ResourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResourceWith applies the HasEdge predicate on the "resource" edge with a given conditions (other predicates).
func HasResourceWith(preds ...predicate.Resource) predicate.ResourceOrder {
	return predicate.ResourceOrder(func(s *sql.Selector) {
		step := newResourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResourceItem applies the HasEdge predicate on the "resource_item" edge.
func HasResourceItem() predicate.ResourceOrder {
	return predicate.ResourceOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ResourceItemTable, ResourceItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResourceItemWith applies the HasEdge predicate on the "resource_item" edge with a given conditions (other predicates).
func HasResourceItemWith(preds ...predicate.ResourceItem) predicate.ResourceOrder {
	return predicate.ResourceOrder(func(s *sql.Selector) {
		step := newResourceItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResourceOrder) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResourceOrder) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResourceOrder) predicate.ResourceOrder {
	return predicate.ResourceOrder(sql.NotPredicates(p))
}
