// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/articlepurchase"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ArticlePurchaseDelete is the builder for deleting a ArticlePurchase entity.
type ArticlePurchaseDelete struct {
	config
	hooks    []Hook
	mutation *ArticlePurchaseMutation
}

// Where appends a list predicates to the ArticlePurchaseDelete builder.
func (apd *ArticlePurchaseDelete) Where(ps ...predicate.ArticlePurchase) *ArticlePurchaseDelete {
	apd.mutation.Where(ps...)
	return apd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (apd *ArticlePurchaseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, apd.sqlExec, apd.mutation, apd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (apd *ArticlePurchaseDelete) ExecX(ctx context.Context) int {
	n, err := apd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (apd *ArticlePurchaseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(articlepurchase.Table, sqlgraph.NewFieldSpec(articlepurchase.FieldID, field.TypeUint))
	if ps := apd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, apd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	apd.mutation.done = true
	return affected, err
}

// ArticlePurchaseDeleteOne is the builder for deleting a single ArticlePurchase entity.
type ArticlePurchaseDeleteOne struct {
	apd *ArticlePurchaseDelete
}

// Where appends a list predicates to the ArticlePurchaseDelete builder.
func (apdo *ArticlePurchaseDeleteOne) Where(ps ...predicate.ArticlePurchase) *ArticlePurchaseDeleteOne {
	apdo.apd.mutation.Where(ps...)
	return apdo
}

// Exec executes the deletion query.
func (apdo *ArticlePurchaseDeleteOne) Exec(ctx context.Context) error {
	n, err := apdo.apd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{articlepurchase.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (apdo *ArticlePurchaseDeleteOne) ExecX(ctx context.Context) {
	if err := apdo.Exec(ctx); err != nil {
		panic(err)
	}
}
