// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/articlepurchase"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ArticlePurchaseUpdate is the builder for updating ArticlePurchase entities.
type ArticlePurchaseUpdate struct {
	config
	hooks     []Hook
	mutation  *ArticlePurchaseMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ArticlePurchaseUpdate builder.
func (apu *ArticlePurchaseUpdate) Where(ps ...predicate.ArticlePurchase) *ArticlePurchaseUpdate {
	apu.mutation.Where(ps...)
	return apu
}

// SetUserID sets the "user_id" field.
func (apu *ArticlePurchaseUpdate) SetUserID(s string) *ArticlePurchaseUpdate {
	apu.mutation.SetUserID(s)
	return apu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (apu *ArticlePurchaseUpdate) SetNillableUserID(s *string) *ArticlePurchaseUpdate {
	if s != nil {
		apu.SetUserID(*s)
	}
	return apu
}

// SetArticleID sets the "article_id" field.
func (apu *ArticlePurchaseUpdate) SetArticleID(u uint) *ArticlePurchaseUpdate {
	apu.mutation.ResetArticleID()
	apu.mutation.SetArticleID(u)
	return apu
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (apu *ArticlePurchaseUpdate) SetNillableArticleID(u *uint) *ArticlePurchaseUpdate {
	if u != nil {
		apu.SetArticleID(*u)
	}
	return apu
}

// AddArticleID adds u to the "article_id" field.
func (apu *ArticlePurchaseUpdate) AddArticleID(u int) *ArticlePurchaseUpdate {
	apu.mutation.AddArticleID(u)
	return apu
}

// SetBlockID sets the "block_id" field.
func (apu *ArticlePurchaseUpdate) SetBlockID(s string) *ArticlePurchaseUpdate {
	apu.mutation.SetBlockID(s)
	return apu
}

// SetNillableBlockID sets the "block_id" field if the given value is not nil.
func (apu *ArticlePurchaseUpdate) SetNillableBlockID(s *string) *ArticlePurchaseUpdate {
	if s != nil {
		apu.SetBlockID(*s)
	}
	return apu
}

// SetPrice sets the "price" field.
func (apu *ArticlePurchaseUpdate) SetPrice(i int) *ArticlePurchaseUpdate {
	apu.mutation.ResetPrice()
	apu.mutation.SetPrice(i)
	return apu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (apu *ArticlePurchaseUpdate) SetNillablePrice(i *int) *ArticlePurchaseUpdate {
	if i != nil {
		apu.SetPrice(*i)
	}
	return apu
}

// AddPrice adds i to the "price" field.
func (apu *ArticlePurchaseUpdate) AddPrice(i int) *ArticlePurchaseUpdate {
	apu.mutation.AddPrice(i)
	return apu
}

// SetOrderNo sets the "order_no" field.
func (apu *ArticlePurchaseUpdate) SetOrderNo(s string) *ArticlePurchaseUpdate {
	apu.mutation.SetOrderNo(s)
	return apu
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (apu *ArticlePurchaseUpdate) SetNillableOrderNo(s *string) *ArticlePurchaseUpdate {
	if s != nil {
		apu.SetOrderNo(*s)
	}
	return apu
}

// ClearOrderNo clears the value of the "order_no" field.
func (apu *ArticlePurchaseUpdate) ClearOrderNo() *ArticlePurchaseUpdate {
	apu.mutation.ClearOrderNo()
	return apu
}

// SetPurchasedAt sets the "purchased_at" field.
func (apu *ArticlePurchaseUpdate) SetPurchasedAt(t time.Time) *ArticlePurchaseUpdate {
	apu.mutation.SetPurchasedAt(t)
	return apu
}

// SetNillablePurchasedAt sets the "purchased_at" field if the given value is not nil.
func (apu *ArticlePurchaseUpdate) SetNillablePurchasedAt(t *time.Time) *ArticlePurchaseUpdate {
	if t != nil {
		apu.SetPurchasedAt(*t)
	}
	return apu
}

// Mutation returns the ArticlePurchaseMutation object of the builder.
func (apu *ArticlePurchaseUpdate) Mutation() *ArticlePurchaseMutation {
	return apu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (apu *ArticlePurchaseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, apu.sqlSave, apu.mutation, apu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (apu *ArticlePurchaseUpdate) SaveX(ctx context.Context) int {
	affected, err := apu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (apu *ArticlePurchaseUpdate) Exec(ctx context.Context) error {
	_, err := apu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apu *ArticlePurchaseUpdate) ExecX(ctx context.Context) {
	if err := apu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apu *ArticlePurchaseUpdate) check() error {
	if v, ok := apu.mutation.UserID(); ok {
		if err := articlepurchase.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ArticlePurchase.user_id": %w`, err)}
		}
	}
	if v, ok := apu.mutation.BlockID(); ok {
		if err := articlepurchase.BlockIDValidator(v); err != nil {
			return &ValidationError{Name: "block_id", err: fmt.Errorf(`ent: validator failed for field "ArticlePurchase.block_id": %w`, err)}
		}
	}
	if v, ok := apu.mutation.Price(); ok {
		if err := articlepurchase.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "ArticlePurchase.price": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (apu *ArticlePurchaseUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArticlePurchaseUpdate {
	apu.modifiers = append(apu.modifiers, modifiers...)
	return apu
}

func (apu *ArticlePurchaseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := apu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(articlepurchase.Table, articlepurchase.Columns, sqlgraph.NewFieldSpec(articlepurchase.FieldID, field.TypeUint))
	if ps := apu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := apu.mutation.UserID(); ok {
		_spec.SetField(articlepurchase.FieldUserID, field.TypeString, value)
	}
	if value, ok := apu.mutation.ArticleID(); ok {
		_spec.SetField(articlepurchase.FieldArticleID, field.TypeUint, value)
	}
	if value, ok := apu.mutation.AddedArticleID(); ok {
		_spec.AddField(articlepurchase.FieldArticleID, field.TypeUint, value)
	}
	if value, ok := apu.mutation.BlockID(); ok {
		_spec.SetField(articlepurchase.FieldBlockID, field.TypeString, value)
	}
	if value, ok := apu.mutation.Price(); ok {
		_spec.SetField(articlepurchase.FieldPrice, field.TypeInt, value)
	}
	if value, ok := apu.mutation.AddedPrice(); ok {
		_spec.AddField(articlepurchase.FieldPrice, field.TypeInt, value)
	}
	if value, ok := apu.mutation.OrderNo(); ok {
		_spec.SetField(articlepurchase.FieldOrderNo, field.TypeString, value)
	}
	if apu.mutation.OrderNoCleared() {
		_spec.ClearField(articlepurchase.FieldOrderNo, field.TypeString)
	}
	if value, ok := apu.mutation.PurchasedAt(); ok {
		_spec.SetField(articlepurchase.FieldPurchasedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(apu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, apu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articlepurchase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	apu.mutation.done = true
	return n, nil
}

// ArticlePurchaseUpdateOne is the builder for updating a single ArticlePurchase entity.
type ArticlePurchaseUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ArticlePurchaseMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (apuo *ArticlePurchaseUpdateOne) SetUserID(s string) *ArticlePurchaseUpdateOne {
	apuo.mutation.SetUserID(s)
	return apuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (apuo *ArticlePurchaseUpdateOne) SetNillableUserID(s *string) *ArticlePurchaseUpdateOne {
	if s != nil {
		apuo.SetUserID(*s)
	}
	return apuo
}

// SetArticleID sets the "article_id" field.
func (apuo *ArticlePurchaseUpdateOne) SetArticleID(u uint) *ArticlePurchaseUpdateOne {
	apuo.mutation.ResetArticleID()
	apuo.mutation.SetArticleID(u)
	return apuo
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (apuo *ArticlePurchaseUpdateOne) SetNillableArticleID(u *uint) *ArticlePurchaseUpdateOne {
	if u != nil {
		apuo.SetArticleID(*u)
	}
	return apuo
}

// AddArticleID adds u to the "article_id" field.
func (apuo *ArticlePurchaseUpdateOne) AddArticleID(u int) *ArticlePurchaseUpdateOne {
	apuo.mutation.AddArticleID(u)
	return apuo
}

// SetBlockID sets the "block_id" field.
func (apuo *ArticlePurchaseUpdateOne) SetBlockID(s string) *ArticlePurchaseUpdateOne {
	apuo.mutation.SetBlockID(s)
	return apuo
}

// SetNillableBlockID sets the "block_id" field if the given value is not nil.
func (apuo *ArticlePurchaseUpdateOne) SetNillableBlockID(s *string) *ArticlePurchaseUpdateOne {
	if s != nil {
		apuo.SetBlockID(*s)
	}
	return apuo
}

// SetPrice sets the "price" field.
func (apuo *ArticlePurchaseUpdateOne) SetPrice(i int) *ArticlePurchaseUpdateOne {
	apuo.mutation.ResetPrice()
	apuo.mutation.SetPrice(i)
	return apuo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (apuo *ArticlePurchaseUpdateOne) SetNillablePrice(i *int) *ArticlePurchaseUpdateOne {
	if i != nil {
		apuo.SetPrice(*i)
	}
	return apuo
}

// AddPrice adds i to the "price" field.
func (apuo *ArticlePurchaseUpdateOne) AddPrice(i int) *ArticlePurchaseUpdateOne {
	apuo.mutation.AddPrice(i)
	return apuo
}

// SetOrderNo sets the "order_no" field.
func (apuo *ArticlePurchaseUpdateOne) SetOrderNo(s string) *ArticlePurchaseUpdateOne {
	apuo.mutation.SetOrderNo(s)
	return apuo
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (apuo *ArticlePurchaseUpdateOne) SetNillableOrderNo(s *string) *ArticlePurchaseUpdateOne {
	if s != nil {
		apuo.SetOrderNo(*s)
	}
	return apuo
}

// ClearOrderNo clears the value of the "order_no" field.
func (apuo *ArticlePurchaseUpdateOne) ClearOrderNo() *ArticlePurchaseUpdateOne {
	apuo.mutation.ClearOrderNo()
	return apuo
}

// SetPurchasedAt sets the "purchased_at" field.
func (apuo *ArticlePurchaseUpdateOne) SetPurchasedAt(t time.Time) *ArticlePurchaseUpdateOne {
	apuo.mutation.SetPurchasedAt(t)
	return apuo
}

// SetNillablePurchasedAt sets the "purchased_at" field if the given value is not nil.
func (apuo *ArticlePurchaseUpdateOne) SetNillablePurchasedAt(t *time.Time) *ArticlePurchaseUpdateOne {
	if t != nil {
		apuo.SetPurchasedAt(*t)
	}
	return apuo
}

// Mutation returns the ArticlePurchaseMutation object of the builder.
func (apuo *ArticlePurchaseUpdateOne) Mutation() *ArticlePurchaseMutation {
	return apuo.mutation
}

// Where appends a list predicates to the ArticlePurchaseUpdate builder.
func (apuo *ArticlePurchaseUpdateOne) Where(ps ...predicate.ArticlePurchase) *ArticlePurchaseUpdateOne {
	apuo.mutation.Where(ps...)
	return apuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (apuo *ArticlePurchaseUpdateOne) Select(field string, fields ...string) *ArticlePurchaseUpdateOne {
	apuo.fields = append([]string{field}, fields...)
	return apuo
}

// Save executes the query and returns the updated ArticlePurchase entity.
func (apuo *ArticlePurchaseUpdateOne) Save(ctx context.Context) (*ArticlePurchase, error) {
	return withHooks(ctx, apuo.sqlSave, apuo.mutation, apuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (apuo *ArticlePurchaseUpdateOne) SaveX(ctx context.Context) *ArticlePurchase {
	node, err := apuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (apuo *ArticlePurchaseUpdateOne) Exec(ctx context.Context) error {
	_, err := apuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apuo *ArticlePurchaseUpdateOne) ExecX(ctx context.Context) {
	if err := apuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apuo *ArticlePurchaseUpdateOne) check() error {
	if v, ok := apuo.mutation.UserID(); ok {
		if err := articlepurchase.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ArticlePurchase.user_id": %w`, err)}
		}
	}
	if v, ok := apuo.mutation.BlockID(); ok {
		if err := articlepurchase.BlockIDValidator(v); err != nil {
			return &ValidationError{Name: "block_id", err: fmt.Errorf(`ent: validator failed for field "ArticlePurchase.block_id": %w`, err)}
		}
	}
	if v, ok := apuo.mutation.Price(); ok {
		if err := articlepurchase.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "ArticlePurchase.price": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (apuo *ArticlePurchaseUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArticlePurchaseUpdateOne {
	apuo.modifiers = append(apuo.modifiers, modifiers...)
	return apuo
}

func (apuo *ArticlePurchaseUpdateOne) sqlSave(ctx context.Context) (_node *ArticlePurchase, err error) {
	if err := apuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(articlepurchase.Table, articlepurchase.Columns, sqlgraph.NewFieldSpec(articlepurchase.FieldID, field.TypeUint))
	id, ok := apuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ArticlePurchase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := apuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, articlepurchase.FieldID)
		for _, f := range fields {
			if !articlepurchase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != articlepurchase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := apuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := apuo.mutation.UserID(); ok {
		_spec.SetField(articlepurchase.FieldUserID, field.TypeString, value)
	}
	if value, ok := apuo.mutation.ArticleID(); ok {
		_spec.SetField(articlepurchase.FieldArticleID, field.TypeUint, value)
	}
	if value, ok := apuo.mutation.AddedArticleID(); ok {
		_spec.AddField(articlepurchase.FieldArticleID, field.TypeUint, value)
	}
	if value, ok := apuo.mutation.BlockID(); ok {
		_spec.SetField(articlepurchase.FieldBlockID, field.TypeString, value)
	}
	if value, ok := apuo.mutation.Price(); ok {
		_spec.SetField(articlepurchase.FieldPrice, field.TypeInt, value)
	}
	if value, ok := apuo.mutation.AddedPrice(); ok {
		_spec.AddField(articlepurchase.FieldPrice, field.TypeInt, value)
	}
	if value, ok := apuo.mutation.OrderNo(); ok {
		_spec.SetField(articlepurchase.FieldOrderNo, field.TypeString, value)
	}
	if apuo.mutation.OrderNoCleared() {
		_spec.ClearField(articlepurchase.FieldOrderNo, field.TypeString)
	}
	if value, ok := apuo.mutation.PurchasedAt(); ok {
		_spec.SetField(articlepurchase.FieldPurchasedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(apuo.modifiers...)
	_node = &ArticlePurchase{config: apuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, apuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articlepurchase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	apuo.mutation.done = true
	return _node, nil
}
