// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/articlepayment"
)

// ArticlePaymentCreate is the builder for creating a ArticlePayment entity.
type ArticlePaymentCreate struct {
	config
	mutation *ArticlePaymentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetArticleID sets the "article_id" field.
func (apc *ArticlePaymentCreate) SetArticleID(u uint) *ArticlePaymentCreate {
	apc.mutation.SetArticleID(u)
	return apc
}

// SetBlockID sets the "block_id" field.
func (apc *ArticlePaymentCreate) SetBlockID(s string) *ArticlePaymentCreate {
	apc.mutation.SetBlockID(s)
	return apc
}

// SetTitle sets the "title" field.
func (apc *ArticlePaymentCreate) SetTitle(s string) *ArticlePaymentCreate {
	apc.mutation.SetTitle(s)
	return apc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (apc *ArticlePaymentCreate) SetNillableTitle(s *string) *ArticlePaymentCreate {
	if s != nil {
		apc.SetTitle(*s)
	}
	return apc
}

// SetPrice sets the "price" field.
func (apc *ArticlePaymentCreate) SetPrice(i int) *ArticlePaymentCreate {
	apc.mutation.SetPrice(i)
	return apc
}

// SetOriginalPrice sets the "original_price" field.
func (apc *ArticlePaymentCreate) SetOriginalPrice(i int) *ArticlePaymentCreate {
	apc.mutation.SetOriginalPrice(i)
	return apc
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (apc *ArticlePaymentCreate) SetNillableOriginalPrice(i *int) *ArticlePaymentCreate {
	if i != nil {
		apc.SetOriginalPrice(*i)
	}
	return apc
}

// SetCurrency sets the "currency" field.
func (apc *ArticlePaymentCreate) SetCurrency(s string) *ArticlePaymentCreate {
	apc.mutation.SetCurrency(s)
	return apc
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (apc *ArticlePaymentCreate) SetNillableCurrency(s *string) *ArticlePaymentCreate {
	if s != nil {
		apc.SetCurrency(*s)
	}
	return apc
}

// SetContentLength sets the "content_length" field.
func (apc *ArticlePaymentCreate) SetContentLength(i int) *ArticlePaymentCreate {
	apc.mutation.SetContentLength(i)
	return apc
}

// SetNillableContentLength sets the "content_length" field if the given value is not nil.
func (apc *ArticlePaymentCreate) SetNillableContentLength(i *int) *ArticlePaymentCreate {
	if i != nil {
		apc.SetContentLength(*i)
	}
	return apc
}

// SetExcludeFromMembership sets the "exclude_from_membership" field.
func (apc *ArticlePaymentCreate) SetExcludeFromMembership(b bool) *ArticlePaymentCreate {
	apc.mutation.SetExcludeFromMembership(b)
	return apc
}

// SetNillableExcludeFromMembership sets the "exclude_from_membership" field if the given value is not nil.
func (apc *ArticlePaymentCreate) SetNillableExcludeFromMembership(b *bool) *ArticlePaymentCreate {
	if b != nil {
		apc.SetExcludeFromMembership(*b)
	}
	return apc
}

// SetCreatedAt sets the "created_at" field.
func (apc *ArticlePaymentCreate) SetCreatedAt(t time.Time) *ArticlePaymentCreate {
	apc.mutation.SetCreatedAt(t)
	return apc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (apc *ArticlePaymentCreate) SetNillableCreatedAt(t *time.Time) *ArticlePaymentCreate {
	if t != nil {
		apc.SetCreatedAt(*t)
	}
	return apc
}

// SetUpdatedAt sets the "updated_at" field.
func (apc *ArticlePaymentCreate) SetUpdatedAt(t time.Time) *ArticlePaymentCreate {
	apc.mutation.SetUpdatedAt(t)
	return apc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (apc *ArticlePaymentCreate) SetNillableUpdatedAt(t *time.Time) *ArticlePaymentCreate {
	if t != nil {
		apc.SetUpdatedAt(*t)
	}
	return apc
}

// SetID sets the "id" field.
func (apc *ArticlePaymentCreate) SetID(u uint) *ArticlePaymentCreate {
	apc.mutation.SetID(u)
	return apc
}

// Mutation returns the ArticlePaymentMutation object of the builder.
func (apc *ArticlePaymentCreate) Mutation() *ArticlePaymentMutation {
	return apc.mutation
}

// Save creates the ArticlePayment in the database.
func (apc *ArticlePaymentCreate) Save(ctx context.Context) (*ArticlePayment, error) {
	apc.defaults()
	return withHooks(ctx, apc.sqlSave, apc.mutation, apc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (apc *ArticlePaymentCreate) SaveX(ctx context.Context) *ArticlePayment {
	v, err := apc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (apc *ArticlePaymentCreate) Exec(ctx context.Context) error {
	_, err := apc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apc *ArticlePaymentCreate) ExecX(ctx context.Context) {
	if err := apc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (apc *ArticlePaymentCreate) defaults() {
	if _, ok := apc.mutation.Title(); !ok {
		v := articlepayment.DefaultTitle
		apc.mutation.SetTitle(v)
	}
	if _, ok := apc.mutation.Currency(); !ok {
		v := articlepayment.DefaultCurrency
		apc.mutation.SetCurrency(v)
	}
	if _, ok := apc.mutation.ContentLength(); !ok {
		v := articlepayment.DefaultContentLength
		apc.mutation.SetContentLength(v)
	}
	if _, ok := apc.mutation.ExcludeFromMembership(); !ok {
		v := articlepayment.DefaultExcludeFromMembership
		apc.mutation.SetExcludeFromMembership(v)
	}
	if _, ok := apc.mutation.CreatedAt(); !ok {
		v := articlepayment.DefaultCreatedAt()
		apc.mutation.SetCreatedAt(v)
	}
	if _, ok := apc.mutation.UpdatedAt(); !ok {
		v := articlepayment.DefaultUpdatedAt()
		apc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apc *ArticlePaymentCreate) check() error {
	if _, ok := apc.mutation.ArticleID(); !ok {
		return &ValidationError{Name: "article_id", err: errors.New(`ent: missing required field "ArticlePayment.article_id"`)}
	}
	if _, ok := apc.mutation.BlockID(); !ok {
		return &ValidationError{Name: "block_id", err: errors.New(`ent: missing required field "ArticlePayment.block_id"`)}
	}
	if v, ok := apc.mutation.BlockID(); ok {
		if err := articlepayment.BlockIDValidator(v); err != nil {
			return &ValidationError{Name: "block_id", err: fmt.Errorf(`ent: validator failed for field "ArticlePayment.block_id": %w`, err)}
		}
	}
	if _, ok := apc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ArticlePayment.title"`)}
	}
	if _, ok := apc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ArticlePayment.price"`)}
	}
	if v, ok := apc.mutation.Price(); ok {
		if err := articlepayment.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "ArticlePayment.price": %w`, err)}
		}
	}
	if v, ok := apc.mutation.OriginalPrice(); ok {
		if err := articlepayment.OriginalPriceValidator(v); err != nil {
			return &ValidationError{Name: "original_price", err: fmt.Errorf(`ent: validator failed for field "ArticlePayment.original_price": %w`, err)}
		}
	}
	if _, ok := apc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "ArticlePayment.currency"`)}
	}
	if _, ok := apc.mutation.ContentLength(); !ok {
		return &ValidationError{Name: "content_length", err: errors.New(`ent: missing required field "ArticlePayment.content_length"`)}
	}
	if v, ok := apc.mutation.ContentLength(); ok {
		if err := articlepayment.ContentLengthValidator(v); err != nil {
			return &ValidationError{Name: "content_length", err: fmt.Errorf(`ent: validator failed for field "ArticlePayment.content_length": %w`, err)}
		}
	}
	if _, ok := apc.mutation.ExcludeFromMembership(); !ok {
		return &ValidationError{Name: "exclude_from_membership", err: errors.New(`ent: missing required field "ArticlePayment.exclude_from_membership"`)}
	}
	if _, ok := apc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ArticlePayment.created_at"`)}
	}
	if _, ok := apc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ArticlePayment.updated_at"`)}
	}
	return nil
}

func (apc *ArticlePaymentCreate) sqlSave(ctx context.Context) (*ArticlePayment, error) {
	if err := apc.check(); err != nil {
		return nil, err
	}
	_node, _spec := apc.createSpec()
	if err := sqlgraph.CreateNode(ctx, apc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	apc.mutation.id = &_node.ID
	apc.mutation.done = true
	return _node, nil
}

func (apc *ArticlePaymentCreate) createSpec() (*ArticlePayment, *sqlgraph.CreateSpec) {
	var (
		_node = &ArticlePayment{config: apc.config}
		_spec = sqlgraph.NewCreateSpec(articlepayment.Table, sqlgraph.NewFieldSpec(articlepayment.FieldID, field.TypeUint))
	)
	_spec.OnConflict = apc.conflict
	if id, ok := apc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := apc.mutation.ArticleID(); ok {
		_spec.SetField(articlepayment.FieldArticleID, field.TypeUint, value)
		_node.ArticleID = value
	}
	if value, ok := apc.mutation.BlockID(); ok {
		_spec.SetField(articlepayment.FieldBlockID, field.TypeString, value)
		_node.BlockID = value
	}
	if value, ok := apc.mutation.Title(); ok {
		_spec.SetField(articlepayment.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := apc.mutation.Price(); ok {
		_spec.SetField(articlepayment.FieldPrice, field.TypeInt, value)
		_node.Price = value
	}
	if value, ok := apc.mutation.OriginalPrice(); ok {
		_spec.SetField(articlepayment.FieldOriginalPrice, field.TypeInt, value)
		_node.OriginalPrice = &value
	}
	if value, ok := apc.mutation.Currency(); ok {
		_spec.SetField(articlepayment.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := apc.mutation.ContentLength(); ok {
		_spec.SetField(articlepayment.FieldContentLength, field.TypeInt, value)
		_node.ContentLength = value
	}
	if value, ok := apc.mutation.ExcludeFromMembership(); ok {
		_spec.SetField(articlepayment.FieldExcludeFromMembership, field.TypeBool, value)
		_node.ExcludeFromMembership = value
	}
	if value, ok := apc.mutation.CreatedAt(); ok {
		_spec.SetField(articlepayment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := apc.mutation.UpdatedAt(); ok {
		_spec.SetField(articlepayment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArticlePayment.Create().
//		SetArticleID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArticlePaymentUpsert) {
//			SetArticleID(v+v).
//		}).
//		Exec(ctx)
func (apc *ArticlePaymentCreate) OnConflict(opts ...sql.ConflictOption) *ArticlePaymentUpsertOne {
	apc.conflict = opts
	return &ArticlePaymentUpsertOne{
		create: apc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArticlePayment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (apc *ArticlePaymentCreate) OnConflictColumns(columns ...string) *ArticlePaymentUpsertOne {
	apc.conflict = append(apc.conflict, sql.ConflictColumns(columns...))
	return &ArticlePaymentUpsertOne{
		create: apc,
	}
}

type (
	// ArticlePaymentUpsertOne is the builder for "upsert"-ing
	//  one ArticlePayment node.
	ArticlePaymentUpsertOne struct {
		create *ArticlePaymentCreate
	}

	// ArticlePaymentUpsert is the "OnConflict" setter.
	ArticlePaymentUpsert struct {
		*sql.UpdateSet
	}
)

// SetArticleID sets the "article_id" field.
func (u *ArticlePaymentUpsert) SetArticleID(v uint) *ArticlePaymentUpsert {
	u.Set(articlepayment.FieldArticleID, v)
	return u
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *ArticlePaymentUpsert) UpdateArticleID() *ArticlePaymentUpsert {
	u.SetExcluded(articlepayment.FieldArticleID)
	return u
}

// AddArticleID adds v to the "article_id" field.
func (u *ArticlePaymentUpsert) AddArticleID(v uint) *ArticlePaymentUpsert {
	u.Add(articlepayment.FieldArticleID, v)
	return u
}

// SetBlockID sets the "block_id" field.
func (u *ArticlePaymentUpsert) SetBlockID(v string) *ArticlePaymentUpsert {
	u.Set(articlepayment.FieldBlockID, v)
	return u
}

// UpdateBlockID sets the "block_id" field to the value that was provided on create.
func (u *ArticlePaymentUpsert) UpdateBlockID() *ArticlePaymentUpsert {
	u.SetExcluded(articlepayment.FieldBlockID)
	return u
}

// SetTitle sets the "title" field.
func (u *ArticlePaymentUpsert) SetTitle(v string) *ArticlePaymentUpsert {
	u.Set(articlepayment.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ArticlePaymentUpsert) UpdateTitle() *ArticlePaymentUpsert {
	u.SetExcluded(articlepayment.FieldTitle)
	return u
}

// SetPrice sets the "price" field.
func (u *ArticlePaymentUpsert) SetPrice(v int) *ArticlePaymentUpsert {
	u.Set(articlepayment.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ArticlePaymentUpsert) UpdatePrice() *ArticlePaymentUpsert {
	u.SetExcluded(articlepayment.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *ArticlePaymentUpsert) AddPrice(v int) *ArticlePaymentUpsert {
	u.Add(articlepayment.FieldPrice, v)
	return u
}

// SetOriginalPrice sets the "original_price" field.
func (u *ArticlePaymentUpsert) SetOriginalPrice(v int) *ArticlePaymentUpsert {
	u.Set(articlepayment.FieldOriginalPrice, v)
	return u
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *ArticlePaymentUpsert) UpdateOriginalPrice() *ArticlePaymentUpsert {
	u.SetExcluded(articlepayment.FieldOriginalPrice)
	return u
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *ArticlePaymentUpsert) AddOriginalPrice(v int) *ArticlePaymentUpsert {
	u.Add(articlepayment.FieldOriginalPrice, v)
	return u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *ArticlePaymentUpsert) ClearOriginalPrice() *ArticlePaymentUpsert {
	u.SetNull(articlepayment.FieldOriginalPrice)
	return u
}

// SetCurrency sets the "currency" field.
func (u *ArticlePaymentUpsert) SetCurrency(v string) *ArticlePaymentUpsert {
	u.Set(articlepayment.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ArticlePaymentUpsert) UpdateCurrency() *ArticlePaymentUpsert {
	u.SetExcluded(articlepayment.FieldCurrency)
	return u
}

// SetContentLength sets the "content_length" field.
func (u *ArticlePaymentUpsert) SetContentLength(v int) *ArticlePaymentUpsert {
	u.Set(articlepayment.FieldContentLength, v)
	return u
}

// UpdateContentLength sets the "content_length" field to the value that was provided on create.
func (u *ArticlePaymentUpsert) UpdateContentLength() *ArticlePaymentUpsert {
	u.SetExcluded(articlepayment.FieldContentLength)
	return u
}

// AddContentLength adds v to the "content_length" field.
func (u *ArticlePaymentUpsert) AddContentLength(v int) *ArticlePaymentUpsert {
	u.Add(articlepayment.FieldContentLength, v)
	return u
}

// SetExcludeFromMembership sets the "exclude_from_membership" field.
func (u *ArticlePaymentUpsert) SetExcludeFromMembership(v bool) *ArticlePaymentUpsert {
	u.Set(articlepayment.FieldExcludeFromMembership, v)
	return u
}

// UpdateExcludeFromMembership sets the "exclude_from_membership" field to the value that was provided on create.
func (u *ArticlePaymentUpsert) UpdateExcludeFromMembership() *ArticlePaymentUpsert {
	u.SetExcluded(articlepayment.FieldExcludeFromMembership)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArticlePaymentUpsert) SetUpdatedAt(v time.Time) *ArticlePaymentUpsert {
	u.Set(articlepayment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArticlePaymentUpsert) UpdateUpdatedAt() *ArticlePaymentUpsert {
	u.SetExcluded(articlepayment.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ArticlePayment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(articlepayment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArticlePaymentUpsertOne) UpdateNewValues() *ArticlePaymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(articlepayment.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(articlepayment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ArticlePayment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ArticlePaymentUpsertOne) Ignore() *ArticlePaymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArticlePaymentUpsertOne) DoNothing() *ArticlePaymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArticlePaymentCreate.OnConflict
// documentation for more info.
func (u *ArticlePaymentUpsertOne) Update(set func(*ArticlePaymentUpsert)) *ArticlePaymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArticlePaymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetArticleID sets the "article_id" field.
func (u *ArticlePaymentUpsertOne) SetArticleID(v uint) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetArticleID(v)
	})
}

// AddArticleID adds v to the "article_id" field.
func (u *ArticlePaymentUpsertOne) AddArticleID(v uint) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.AddArticleID(v)
	})
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *ArticlePaymentUpsertOne) UpdateArticleID() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateArticleID()
	})
}

// SetBlockID sets the "block_id" field.
func (u *ArticlePaymentUpsertOne) SetBlockID(v string) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetBlockID(v)
	})
}

// UpdateBlockID sets the "block_id" field to the value that was provided on create.
func (u *ArticlePaymentUpsertOne) UpdateBlockID() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateBlockID()
	})
}

// SetTitle sets the "title" field.
func (u *ArticlePaymentUpsertOne) SetTitle(v string) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ArticlePaymentUpsertOne) UpdateTitle() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateTitle()
	})
}

// SetPrice sets the "price" field.
func (u *ArticlePaymentUpsertOne) SetPrice(v int) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ArticlePaymentUpsertOne) AddPrice(v int) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ArticlePaymentUpsertOne) UpdatePrice() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdatePrice()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *ArticlePaymentUpsertOne) SetOriginalPrice(v int) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *ArticlePaymentUpsertOne) AddOriginalPrice(v int) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *ArticlePaymentUpsertOne) UpdateOriginalPrice() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *ArticlePaymentUpsertOne) ClearOriginalPrice() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *ArticlePaymentUpsertOne) SetCurrency(v string) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ArticlePaymentUpsertOne) UpdateCurrency() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateCurrency()
	})
}

// SetContentLength sets the "content_length" field.
func (u *ArticlePaymentUpsertOne) SetContentLength(v int) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetContentLength(v)
	})
}

// AddContentLength adds v to the "content_length" field.
func (u *ArticlePaymentUpsertOne) AddContentLength(v int) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.AddContentLength(v)
	})
}

// UpdateContentLength sets the "content_length" field to the value that was provided on create.
func (u *ArticlePaymentUpsertOne) UpdateContentLength() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateContentLength()
	})
}

// SetExcludeFromMembership sets the "exclude_from_membership" field.
func (u *ArticlePaymentUpsertOne) SetExcludeFromMembership(v bool) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetExcludeFromMembership(v)
	})
}

// UpdateExcludeFromMembership sets the "exclude_from_membership" field to the value that was provided on create.
func (u *ArticlePaymentUpsertOne) UpdateExcludeFromMembership() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateExcludeFromMembership()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArticlePaymentUpsertOne) SetUpdatedAt(v time.Time) *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArticlePaymentUpsertOne) UpdateUpdatedAt() *ArticlePaymentUpsertOne {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ArticlePaymentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArticlePaymentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArticlePaymentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ArticlePaymentUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ArticlePaymentUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ArticlePaymentCreateBulk is the builder for creating many ArticlePayment entities in bulk.
type ArticlePaymentCreateBulk struct {
	config
	err      error
	builders []*ArticlePaymentCreate
	conflict []sql.ConflictOption
}

// Save creates the ArticlePayment entities in the database.
func (apcb *ArticlePaymentCreateBulk) Save(ctx context.Context) ([]*ArticlePayment, error) {
	if apcb.err != nil {
		return nil, apcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(apcb.builders))
	nodes := make([]*ArticlePayment, len(apcb.builders))
	mutators := make([]Mutator, len(apcb.builders))
	for i := range apcb.builders {
		func(i int, root context.Context) {
			builder := apcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArticlePaymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, apcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = apcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, apcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, apcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (apcb *ArticlePaymentCreateBulk) SaveX(ctx context.Context) []*ArticlePayment {
	v, err := apcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (apcb *ArticlePaymentCreateBulk) Exec(ctx context.Context) error {
	_, err := apcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apcb *ArticlePaymentCreateBulk) ExecX(ctx context.Context) {
	if err := apcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArticlePayment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArticlePaymentUpsert) {
//			SetArticleID(v+v).
//		}).
//		Exec(ctx)
func (apcb *ArticlePaymentCreateBulk) OnConflict(opts ...sql.ConflictOption) *ArticlePaymentUpsertBulk {
	apcb.conflict = opts
	return &ArticlePaymentUpsertBulk{
		create: apcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArticlePayment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (apcb *ArticlePaymentCreateBulk) OnConflictColumns(columns ...string) *ArticlePaymentUpsertBulk {
	apcb.conflict = append(apcb.conflict, sql.ConflictColumns(columns...))
	return &ArticlePaymentUpsertBulk{
		create: apcb,
	}
}

// ArticlePaymentUpsertBulk is the builder for "upsert"-ing
// a bulk of ArticlePayment nodes.
type ArticlePaymentUpsertBulk struct {
	create *ArticlePaymentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ArticlePayment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(articlepayment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArticlePaymentUpsertBulk) UpdateNewValues() *ArticlePaymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(articlepayment.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(articlepayment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ArticlePayment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ArticlePaymentUpsertBulk) Ignore() *ArticlePaymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArticlePaymentUpsertBulk) DoNothing() *ArticlePaymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArticlePaymentCreateBulk.OnConflict
// documentation for more info.
func (u *ArticlePaymentUpsertBulk) Update(set func(*ArticlePaymentUpsert)) *ArticlePaymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArticlePaymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetArticleID sets the "article_id" field.
func (u *ArticlePaymentUpsertBulk) SetArticleID(v uint) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetArticleID(v)
	})
}

// AddArticleID adds v to the "article_id" field.
func (u *ArticlePaymentUpsertBulk) AddArticleID(v uint) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.AddArticleID(v)
	})
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *ArticlePaymentUpsertBulk) UpdateArticleID() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateArticleID()
	})
}

// SetBlockID sets the "block_id" field.
func (u *ArticlePaymentUpsertBulk) SetBlockID(v string) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetBlockID(v)
	})
}

// UpdateBlockID sets the "block_id" field to the value that was provided on create.
func (u *ArticlePaymentUpsertBulk) UpdateBlockID() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateBlockID()
	})
}

// SetTitle sets the "title" field.
func (u *ArticlePaymentUpsertBulk) SetTitle(v string) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ArticlePaymentUpsertBulk) UpdateTitle() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateTitle()
	})
}

// SetPrice sets the "price" field.
func (u *ArticlePaymentUpsertBulk) SetPrice(v int) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ArticlePaymentUpsertBulk) AddPrice(v int) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ArticlePaymentUpsertBulk) UpdatePrice() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdatePrice()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *ArticlePaymentUpsertBulk) SetOriginalPrice(v int) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *ArticlePaymentUpsertBulk) AddOriginalPrice(v int) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *ArticlePaymentUpsertBulk) UpdateOriginalPrice() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *ArticlePaymentUpsertBulk) ClearOriginalPrice() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *ArticlePaymentUpsertBulk) SetCurrency(v string) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ArticlePaymentUpsertBulk) UpdateCurrency() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateCurrency()
	})
}

// SetContentLength sets the "content_length" field.
func (u *ArticlePaymentUpsertBulk) SetContentLength(v int) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetContentLength(v)
	})
}

// AddContentLength adds v to the "content_length" field.
func (u *ArticlePaymentUpsertBulk) AddContentLength(v int) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.AddContentLength(v)
	})
}

// UpdateContentLength sets the "content_length" field to the value that was provided on create.
func (u *ArticlePaymentUpsertBulk) UpdateContentLength() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateContentLength()
	})
}

// SetExcludeFromMembership sets the "exclude_from_membership" field.
func (u *ArticlePaymentUpsertBulk) SetExcludeFromMembership(v bool) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetExcludeFromMembership(v)
	})
}

// UpdateExcludeFromMembership sets the "exclude_from_membership" field to the value that was provided on create.
func (u *ArticlePaymentUpsertBulk) UpdateExcludeFromMembership() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateExcludeFromMembership()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArticlePaymentUpsertBulk) SetUpdatedAt(v time.Time) *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArticlePaymentUpsertBulk) UpdateUpdatedAt() *ArticlePaymentUpsertBulk {
	return u.Update(func(s *ArticlePaymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ArticlePaymentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ArticlePaymentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArticlePaymentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArticlePaymentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
