// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/articlepurchase"
)

// ArticlePurchaseCreate is the builder for creating a ArticlePurchase entity.
type ArticlePurchaseCreate struct {
	config
	mutation *ArticlePurchaseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (apc *ArticlePurchaseCreate) SetUserID(s string) *ArticlePurchaseCreate {
	apc.mutation.SetUserID(s)
	return apc
}

// SetArticleID sets the "article_id" field.
func (apc *ArticlePurchaseCreate) SetArticleID(u uint) *ArticlePurchaseCreate {
	apc.mutation.SetArticleID(u)
	return apc
}

// SetBlockID sets the "block_id" field.
func (apc *ArticlePurchaseCreate) SetBlockID(s string) *ArticlePurchaseCreate {
	apc.mutation.SetBlockID(s)
	return apc
}

// SetPrice sets the "price" field.
func (apc *ArticlePurchaseCreate) SetPrice(i int) *ArticlePurchaseCreate {
	apc.mutation.SetPrice(i)
	return apc
}

// SetOrderNo sets the "order_no" field.
func (apc *ArticlePurchaseCreate) SetOrderNo(s string) *ArticlePurchaseCreate {
	apc.mutation.SetOrderNo(s)
	return apc
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (apc *ArticlePurchaseCreate) SetNillableOrderNo(s *string) *ArticlePurchaseCreate {
	if s != nil {
		apc.SetOrderNo(*s)
	}
	return apc
}

// SetPurchasedAt sets the "purchased_at" field.
func (apc *ArticlePurchaseCreate) SetPurchasedAt(t time.Time) *ArticlePurchaseCreate {
	apc.mutation.SetPurchasedAt(t)
	return apc
}

// SetNillablePurchasedAt sets the "purchased_at" field if the given value is not nil.
func (apc *ArticlePurchaseCreate) SetNillablePurchasedAt(t *time.Time) *ArticlePurchaseCreate {
	if t != nil {
		apc.SetPurchasedAt(*t)
	}
	return apc
}

// SetID sets the "id" field.
func (apc *ArticlePurchaseCreate) SetID(u uint) *ArticlePurchaseCreate {
	apc.mutation.SetID(u)
	return apc
}

// Mutation returns the ArticlePurchaseMutation object of the builder.
func (apc *ArticlePurchaseCreate) Mutation() *ArticlePurchaseMutation {
	return apc.mutation
}

// Save creates the ArticlePurchase in the database.
func (apc *ArticlePurchaseCreate) Save(ctx context.Context) (*ArticlePurchase, error) {
	apc.defaults()
	return withHooks(ctx, apc.sqlSave, apc.mutation, apc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (apc *ArticlePurchaseCreate) SaveX(ctx context.Context) *ArticlePurchase {
	v, err := apc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (apc *ArticlePurchaseCreate) Exec(ctx context.Context) error {
	_, err := apc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apc *ArticlePurchaseCreate) ExecX(ctx context.Context) {
	if err := apc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (apc *ArticlePurchaseCreate) defaults() {
	if _, ok := apc.mutation.PurchasedAt(); !ok {
		v := articlepurchase.DefaultPurchasedAt()
		apc.mutation.SetPurchasedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apc *ArticlePurchaseCreate) check() error {
	if _, ok := apc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ArticlePurchase.user_id"`)}
	}
	if v, ok := apc.mutation.UserID(); ok {
		if err := articlepurchase.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ArticlePurchase.user_id": %w`, err)}
		}
	}
	if _, ok := apc.mutation.ArticleID(); !ok {
		return &ValidationError{Name: "article_id", err: errors.New(`ent: missing required field "ArticlePurchase.article_id"`)}
	}
	if _, ok := apc.mutation.BlockID(); !ok {
		return &ValidationError{Name: "block_id", err: errors.New(`ent: missing required field "ArticlePurchase.block_id"`)}
	}
	if v, ok := apc.mutation.BlockID(); ok {
		if err := articlepurchase.BlockIDValidator(v); err != nil {
			return &ValidationError{Name: "block_id", err: fmt.Errorf(`ent: validator failed for field "ArticlePurchase.block_id": %w`, err)}
		}
	}
	if _, ok := apc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ArticlePurchase.price"`)}
	}
	if v, ok := apc.mutation.Price(); ok {
		if err := articlepurchase.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "ArticlePurchase.price": %w`, err)}
		}
	}
	if _, ok := apc.mutation.PurchasedAt(); !ok {
		return &ValidationError{Name: "purchased_at", err: errors.New(`ent: missing required field "ArticlePurchase.purchased_at"`)}
	}
	return nil
}

func (apc *ArticlePurchaseCreate) sqlSave(ctx context.Context) (*ArticlePurchase, error) {
	if err := apc.check(); err != nil {
		return nil, err
	}
	_node, _spec := apc.createSpec()
	if err := sqlgraph.CreateNode(ctx, apc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	apc.mutation.id = &_node.ID
	apc.mutation.done = true
	return _node, nil
}

func (apc *ArticlePurchaseCreate) createSpec() (*ArticlePurchase, *sqlgraph.CreateSpec) {
	var (
		_node = &ArticlePurchase{config: apc.config}
		_spec = sqlgraph.NewCreateSpec(articlepurchase.Table, sqlgraph.NewFieldSpec(articlepurchase.FieldID, field.TypeUint))
	)
	_spec.OnConflict = apc.conflict
	if id, ok := apc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := apc.mutation.UserID(); ok {
		_spec.SetField(articlepurchase.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := apc.mutation.ArticleID(); ok {
		_spec.SetField(articlepurchase.FieldArticleID, field.TypeUint, value)
		_node.ArticleID = value
	}
	if value, ok := apc.mutation.BlockID(); ok {
		_spec.SetField(articlepurchase.FieldBlockID, field.TypeString, value)
		_node.BlockID = value
	}
	if value, ok := apc.mutation.Price(); ok {
		_spec.SetField(articlepurchase.FieldPrice, field.TypeInt, value)
		_node.Price = value
	}
	if value, ok := apc.mutation.OrderNo(); ok {
		_spec.SetField(articlepurchase.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = &value
	}
	if value, ok := apc.mutation.PurchasedAt(); ok {
		_spec.SetField(articlepurchase.FieldPurchasedAt, field.TypeTime, value)
		_node.PurchasedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArticlePurchase.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArticlePurchaseUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (apc *ArticlePurchaseCreate) OnConflict(opts ...sql.ConflictOption) *ArticlePurchaseUpsertOne {
	apc.conflict = opts
	return &ArticlePurchaseUpsertOne{
		create: apc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArticlePurchase.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (apc *ArticlePurchaseCreate) OnConflictColumns(columns ...string) *ArticlePurchaseUpsertOne {
	apc.conflict = append(apc.conflict, sql.ConflictColumns(columns...))
	return &ArticlePurchaseUpsertOne{
		create: apc,
	}
}

type (
	// ArticlePurchaseUpsertOne is the builder for "upsert"-ing
	//  one ArticlePurchase node.
	ArticlePurchaseUpsertOne struct {
		create *ArticlePurchaseCreate
	}

	// ArticlePurchaseUpsert is the "OnConflict" setter.
	ArticlePurchaseUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *ArticlePurchaseUpsert) SetUserID(v string) *ArticlePurchaseUpsert {
	u.Set(articlepurchase.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ArticlePurchaseUpsert) UpdateUserID() *ArticlePurchaseUpsert {
	u.SetExcluded(articlepurchase.FieldUserID)
	return u
}

// SetArticleID sets the "article_id" field.
func (u *ArticlePurchaseUpsert) SetArticleID(v uint) *ArticlePurchaseUpsert {
	u.Set(articlepurchase.FieldArticleID, v)
	return u
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *ArticlePurchaseUpsert) UpdateArticleID() *ArticlePurchaseUpsert {
	u.SetExcluded(articlepurchase.FieldArticleID)
	return u
}

// AddArticleID adds v to the "article_id" field.
func (u *ArticlePurchaseUpsert) AddArticleID(v uint) *ArticlePurchaseUpsert {
	u.Add(articlepurchase.FieldArticleID, v)
	return u
}

// SetBlockID sets the "block_id" field.
func (u *ArticlePurchaseUpsert) SetBlockID(v string) *ArticlePurchaseUpsert {
	u.Set(articlepurchase.FieldBlockID, v)
	return u
}

// UpdateBlockID sets the "block_id" field to the value that was provided on create.
func (u *ArticlePurchaseUpsert) UpdateBlockID() *ArticlePurchaseUpsert {
	u.SetExcluded(articlepurchase.FieldBlockID)
	return u
}

// SetPrice sets the "price" field.
func (u *ArticlePurchaseUpsert) SetPrice(v int) *ArticlePurchaseUpsert {
	u.Set(articlepurchase.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ArticlePurchaseUpsert) UpdatePrice() *ArticlePurchaseUpsert {
	u.SetExcluded(articlepurchase.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *ArticlePurchaseUpsert) AddPrice(v int) *ArticlePurchaseUpsert {
	u.Add(articlepurchase.FieldPrice, v)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *ArticlePurchaseUpsert) SetOrderNo(v string) *ArticlePurchaseUpsert {
	u.Set(articlepurchase.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *ArticlePurchaseUpsert) UpdateOrderNo() *ArticlePurchaseUpsert {
	u.SetExcluded(articlepurchase.FieldOrderNo)
	return u
}

// ClearOrderNo clears the value of the "order_no" field.
func (u *ArticlePurchaseUpsert) ClearOrderNo() *ArticlePurchaseUpsert {
	u.SetNull(articlepurchase.FieldOrderNo)
	return u
}

// SetPurchasedAt sets the "purchased_at" field.
func (u *ArticlePurchaseUpsert) SetPurchasedAt(v time.Time) *ArticlePurchaseUpsert {
	u.Set(articlepurchase.FieldPurchasedAt, v)
	return u
}

// UpdatePurchasedAt sets the "purchased_at" field to the value that was provided on create.
func (u *ArticlePurchaseUpsert) UpdatePurchasedAt() *ArticlePurchaseUpsert {
	u.SetExcluded(articlepurchase.FieldPurchasedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ArticlePurchase.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(articlepurchase.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArticlePurchaseUpsertOne) UpdateNewValues() *ArticlePurchaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(articlepurchase.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ArticlePurchase.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ArticlePurchaseUpsertOne) Ignore() *ArticlePurchaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArticlePurchaseUpsertOne) DoNothing() *ArticlePurchaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArticlePurchaseCreate.OnConflict
// documentation for more info.
func (u *ArticlePurchaseUpsertOne) Update(set func(*ArticlePurchaseUpsert)) *ArticlePurchaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArticlePurchaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ArticlePurchaseUpsertOne) SetUserID(v string) *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertOne) UpdateUserID() *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdateUserID()
	})
}

// SetArticleID sets the "article_id" field.
func (u *ArticlePurchaseUpsertOne) SetArticleID(v uint) *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetArticleID(v)
	})
}

// AddArticleID adds v to the "article_id" field.
func (u *ArticlePurchaseUpsertOne) AddArticleID(v uint) *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.AddArticleID(v)
	})
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertOne) UpdateArticleID() *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdateArticleID()
	})
}

// SetBlockID sets the "block_id" field.
func (u *ArticlePurchaseUpsertOne) SetBlockID(v string) *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetBlockID(v)
	})
}

// UpdateBlockID sets the "block_id" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertOne) UpdateBlockID() *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdateBlockID()
	})
}

// SetPrice sets the "price" field.
func (u *ArticlePurchaseUpsertOne) SetPrice(v int) *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ArticlePurchaseUpsertOne) AddPrice(v int) *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertOne) UpdatePrice() *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdatePrice()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *ArticlePurchaseUpsertOne) SetOrderNo(v string) *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertOne) UpdateOrderNo() *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdateOrderNo()
	})
}

// ClearOrderNo clears the value of the "order_no" field.
func (u *ArticlePurchaseUpsertOne) ClearOrderNo() *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.ClearOrderNo()
	})
}

// SetPurchasedAt sets the "purchased_at" field.
func (u *ArticlePurchaseUpsertOne) SetPurchasedAt(v time.Time) *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetPurchasedAt(v)
	})
}

// UpdatePurchasedAt sets the "purchased_at" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertOne) UpdatePurchasedAt() *ArticlePurchaseUpsertOne {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdatePurchasedAt()
	})
}

// Exec executes the query.
func (u *ArticlePurchaseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArticlePurchaseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArticlePurchaseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ArticlePurchaseUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ArticlePurchaseUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ArticlePurchaseCreateBulk is the builder for creating many ArticlePurchase entities in bulk.
type ArticlePurchaseCreateBulk struct {
	config
	err      error
	builders []*ArticlePurchaseCreate
	conflict []sql.ConflictOption
}

// Save creates the ArticlePurchase entities in the database.
func (apcb *ArticlePurchaseCreateBulk) Save(ctx context.Context) ([]*ArticlePurchase, error) {
	if apcb.err != nil {
		return nil, apcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(apcb.builders))
	nodes := make([]*ArticlePurchase, len(apcb.builders))
	mutators := make([]Mutator, len(apcb.builders))
	for i := range apcb.builders {
		func(i int, root context.Context) {
			builder := apcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArticlePurchaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, apcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = apcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, apcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, apcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (apcb *ArticlePurchaseCreateBulk) SaveX(ctx context.Context) []*ArticlePurchase {
	v, err := apcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (apcb *ArticlePurchaseCreateBulk) Exec(ctx context.Context) error {
	_, err := apcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apcb *ArticlePurchaseCreateBulk) ExecX(ctx context.Context) {
	if err := apcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArticlePurchase.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArticlePurchaseUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (apcb *ArticlePurchaseCreateBulk) OnConflict(opts ...sql.ConflictOption) *ArticlePurchaseUpsertBulk {
	apcb.conflict = opts
	return &ArticlePurchaseUpsertBulk{
		create: apcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArticlePurchase.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (apcb *ArticlePurchaseCreateBulk) OnConflictColumns(columns ...string) *ArticlePurchaseUpsertBulk {
	apcb.conflict = append(apcb.conflict, sql.ConflictColumns(columns...))
	return &ArticlePurchaseUpsertBulk{
		create: apcb,
	}
}

// ArticlePurchaseUpsertBulk is the builder for "upsert"-ing
// a bulk of ArticlePurchase nodes.
type ArticlePurchaseUpsertBulk struct {
	create *ArticlePurchaseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ArticlePurchase.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(articlepurchase.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArticlePurchaseUpsertBulk) UpdateNewValues() *ArticlePurchaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(articlepurchase.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ArticlePurchase.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ArticlePurchaseUpsertBulk) Ignore() *ArticlePurchaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArticlePurchaseUpsertBulk) DoNothing() *ArticlePurchaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArticlePurchaseCreateBulk.OnConflict
// documentation for more info.
func (u *ArticlePurchaseUpsertBulk) Update(set func(*ArticlePurchaseUpsert)) *ArticlePurchaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArticlePurchaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ArticlePurchaseUpsertBulk) SetUserID(v string) *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertBulk) UpdateUserID() *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdateUserID()
	})
}

// SetArticleID sets the "article_id" field.
func (u *ArticlePurchaseUpsertBulk) SetArticleID(v uint) *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetArticleID(v)
	})
}

// AddArticleID adds v to the "article_id" field.
func (u *ArticlePurchaseUpsertBulk) AddArticleID(v uint) *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.AddArticleID(v)
	})
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertBulk) UpdateArticleID() *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdateArticleID()
	})
}

// SetBlockID sets the "block_id" field.
func (u *ArticlePurchaseUpsertBulk) SetBlockID(v string) *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetBlockID(v)
	})
}

// UpdateBlockID sets the "block_id" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertBulk) UpdateBlockID() *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdateBlockID()
	})
}

// SetPrice sets the "price" field.
func (u *ArticlePurchaseUpsertBulk) SetPrice(v int) *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ArticlePurchaseUpsertBulk) AddPrice(v int) *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertBulk) UpdatePrice() *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdatePrice()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *ArticlePurchaseUpsertBulk) SetOrderNo(v string) *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertBulk) UpdateOrderNo() *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdateOrderNo()
	})
}

// ClearOrderNo clears the value of the "order_no" field.
func (u *ArticlePurchaseUpsertBulk) ClearOrderNo() *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.ClearOrderNo()
	})
}

// SetPurchasedAt sets the "purchased_at" field.
func (u *ArticlePurchaseUpsertBulk) SetPurchasedAt(v time.Time) *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.SetPurchasedAt(v)
	})
}

// UpdatePurchasedAt sets the "purchased_at" field to the value that was provided on create.
func (u *ArticlePurchaseUpsertBulk) UpdatePurchasedAt() *ArticlePurchaseUpsertBulk {
	return u.Update(func(s *ArticlePurchaseUpsert) {
		s.UpdatePurchasedAt()
	})
}

// Exec executes the query.
func (u *ArticlePurchaseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ArticlePurchaseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArticlePurchaseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArticlePurchaseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
