// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/articlepurchase"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ArticlePurchaseQuery is the builder for querying ArticlePurchase entities.
type ArticlePurchaseQuery struct {
	config
	ctx        *QueryContext
	order      []articlepurchase.OrderOption
	inters     []Interceptor
	predicates []predicate.ArticlePurchase
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ArticlePurchaseQuery builder.
func (apq *ArticlePurchaseQuery) Where(ps ...predicate.ArticlePurchase) *ArticlePurchaseQuery {
	apq.predicates = append(apq.predicates, ps...)
	return apq
}

// Limit the number of records to be returned by this query.
func (apq *ArticlePurchaseQuery) Limit(limit int) *ArticlePurchaseQuery {
	apq.ctx.Limit = &limit
	return apq
}

// Offset to start from.
func (apq *ArticlePurchaseQuery) Offset(offset int) *ArticlePurchaseQuery {
	apq.ctx.Offset = &offset
	return apq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (apq *ArticlePurchaseQuery) Unique(unique bool) *ArticlePurchaseQuery {
	apq.ctx.Unique = &unique
	return apq
}

// Order specifies how the records should be ordered.
func (apq *ArticlePurchaseQuery) Order(o ...articlepurchase.OrderOption) *ArticlePurchaseQuery {
	apq.order = append(apq.order, o...)
	return apq
}

// First returns the first ArticlePurchase entity from the query.
// Returns a *NotFoundError when no ArticlePurchase was found.
func (apq *ArticlePurchaseQuery) First(ctx context.Context) (*ArticlePurchase, error) {
	nodes, err := apq.Limit(1).All(setContextOp(ctx, apq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{articlepurchase.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (apq *ArticlePurchaseQuery) FirstX(ctx context.Context) *ArticlePurchase {
	node, err := apq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ArticlePurchase ID from the query.
// Returns a *NotFoundError when no ArticlePurchase ID was found.
func (apq *ArticlePurchaseQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = apq.Limit(1).IDs(setContextOp(ctx, apq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{articlepurchase.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (apq *ArticlePurchaseQuery) FirstIDX(ctx context.Context) uint {
	id, err := apq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ArticlePurchase entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ArticlePurchase entity is found.
// Returns a *NotFoundError when no ArticlePurchase entities are found.
func (apq *ArticlePurchaseQuery) Only(ctx context.Context) (*ArticlePurchase, error) {
	nodes, err := apq.Limit(2).All(setContextOp(ctx, apq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{articlepurchase.Label}
	default:
		return nil, &NotSingularError{articlepurchase.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (apq *ArticlePurchaseQuery) OnlyX(ctx context.Context) *ArticlePurchase {
	node, err := apq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ArticlePurchase ID in the query.
// Returns a *NotSingularError when more than one ArticlePurchase ID is found.
// Returns a *NotFoundError when no entities are found.
func (apq *ArticlePurchaseQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = apq.Limit(2).IDs(setContextOp(ctx, apq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{articlepurchase.Label}
	default:
		err = &NotSingularError{articlepurchase.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (apq *ArticlePurchaseQuery) OnlyIDX(ctx context.Context) uint {
	id, err := apq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ArticlePurchases.
func (apq *ArticlePurchaseQuery) All(ctx context.Context) ([]*ArticlePurchase, error) {
	ctx = setContextOp(ctx, apq.ctx, ent.OpQueryAll)
	if err := apq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ArticlePurchase, *ArticlePurchaseQuery]()
	return withInterceptors[[]*ArticlePurchase](ctx, apq, qr, apq.inters)
}

// AllX is like All, but panics if an error occurs.
func (apq *ArticlePurchaseQuery) AllX(ctx context.Context) []*ArticlePurchase {
	nodes, err := apq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ArticlePurchase IDs.
func (apq *ArticlePurchaseQuery) IDs(ctx context.Context) (ids []uint, err error) {
	if apq.ctx.Unique == nil && apq.path != nil {
		apq.Unique(true)
	}
	ctx = setContextOp(ctx, apq.ctx, ent.OpQueryIDs)
	if err = apq.Select(articlepurchase.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (apq *ArticlePurchaseQuery) IDsX(ctx context.Context) []uint {
	ids, err := apq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (apq *ArticlePurchaseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, apq.ctx, ent.OpQueryCount)
	if err := apq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, apq, querierCount[*ArticlePurchaseQuery](), apq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (apq *ArticlePurchaseQuery) CountX(ctx context.Context) int {
	count, err := apq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (apq *ArticlePurchaseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, apq.ctx, ent.OpQueryExist)
	switch _, err := apq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (apq *ArticlePurchaseQuery) ExistX(ctx context.Context) bool {
	exist, err := apq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ArticlePurchaseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (apq *ArticlePurchaseQuery) Clone() *ArticlePurchaseQuery {
	if apq == nil {
		return nil
	}
	return &ArticlePurchaseQuery{
		config:     apq.config,
		ctx:        apq.ctx.Clone(),
		order:      append([]articlepurchase.OrderOption{}, apq.order...),
		inters:     append([]Interceptor{}, apq.inters...),
		predicates: append([]predicate.ArticlePurchase{}, apq.predicates...),
		// clone intermediate query.
		sql:       apq.sql.Clone(),
		path:      apq.path,
		modifiers: append([]func(*sql.Selector){}, apq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ArticlePurchase.Query().
//		GroupBy(articlepurchase.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (apq *ArticlePurchaseQuery) GroupBy(field string, fields ...string) *ArticlePurchaseGroupBy {
	apq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ArticlePurchaseGroupBy{build: apq}
	grbuild.flds = &apq.ctx.Fields
	grbuild.label = articlepurchase.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.ArticlePurchase.Query().
//		Select(articlepurchase.FieldUserID).
//		Scan(ctx, &v)
func (apq *ArticlePurchaseQuery) Select(fields ...string) *ArticlePurchaseSelect {
	apq.ctx.Fields = append(apq.ctx.Fields, fields...)
	sbuild := &ArticlePurchaseSelect{ArticlePurchaseQuery: apq}
	sbuild.label = articlepurchase.Label
	sbuild.flds, sbuild.scan = &apq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ArticlePurchaseSelect configured with the given aggregations.
func (apq *ArticlePurchaseQuery) Aggregate(fns ...AggregateFunc) *ArticlePurchaseSelect {
	return apq.Select().Aggregate(fns...)
}

func (apq *ArticlePurchaseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range apq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, apq); err != nil {
				return err
			}
		}
	}
	for _, f := range apq.ctx.Fields {
		if !articlepurchase.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if apq.path != nil {
		prev, err := apq.path(ctx)
		if err != nil {
			return err
		}
		apq.sql = prev
	}
	return nil
}

func (apq *ArticlePurchaseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ArticlePurchase, error) {
	var (
		nodes = []*ArticlePurchase{}
		_spec = apq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ArticlePurchase).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ArticlePurchase{config: apq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(apq.modifiers) > 0 {
		_spec.Modifiers = apq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, apq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (apq *ArticlePurchaseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := apq.querySpec()
	if len(apq.modifiers) > 0 {
		_spec.Modifiers = apq.modifiers
	}
	_spec.Node.Columns = apq.ctx.Fields
	if len(apq.ctx.Fields) > 0 {
		_spec.Unique = apq.ctx.Unique != nil && *apq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, apq.driver, _spec)
}

func (apq *ArticlePurchaseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(articlepurchase.Table, articlepurchase.Columns, sqlgraph.NewFieldSpec(articlepurchase.FieldID, field.TypeUint))
	_spec.From = apq.sql
	if unique := apq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if apq.path != nil {
		_spec.Unique = true
	}
	if fields := apq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, articlepurchase.FieldID)
		for i := range fields {
			if fields[i] != articlepurchase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := apq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := apq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := apq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := apq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (apq *ArticlePurchaseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(apq.driver.Dialect())
	t1 := builder.Table(articlepurchase.Table)
	columns := apq.ctx.Fields
	if len(columns) == 0 {
		columns = articlepurchase.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if apq.sql != nil {
		selector = apq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if apq.ctx.Unique != nil && *apq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range apq.modifiers {
		m(selector)
	}
	for _, p := range apq.predicates {
		p(selector)
	}
	for _, p := range apq.order {
		p(selector)
	}
	if offset := apq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := apq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (apq *ArticlePurchaseQuery) Modify(modifiers ...func(s *sql.Selector)) *ArticlePurchaseSelect {
	apq.modifiers = append(apq.modifiers, modifiers...)
	return apq.Select()
}

// ArticlePurchaseGroupBy is the group-by builder for ArticlePurchase entities.
type ArticlePurchaseGroupBy struct {
	selector
	build *ArticlePurchaseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (apgb *ArticlePurchaseGroupBy) Aggregate(fns ...AggregateFunc) *ArticlePurchaseGroupBy {
	apgb.fns = append(apgb.fns, fns...)
	return apgb
}

// Scan applies the selector query and scans the result into the given value.
func (apgb *ArticlePurchaseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, apgb.build.ctx, ent.OpQueryGroupBy)
	if err := apgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ArticlePurchaseQuery, *ArticlePurchaseGroupBy](ctx, apgb.build, apgb, apgb.build.inters, v)
}

func (apgb *ArticlePurchaseGroupBy) sqlScan(ctx context.Context, root *ArticlePurchaseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(apgb.fns))
	for _, fn := range apgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*apgb.flds)+len(apgb.fns))
		for _, f := range *apgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*apgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := apgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ArticlePurchaseSelect is the builder for selecting fields of ArticlePurchase entities.
type ArticlePurchaseSelect struct {
	*ArticlePurchaseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aps *ArticlePurchaseSelect) Aggregate(fns ...AggregateFunc) *ArticlePurchaseSelect {
	aps.fns = append(aps.fns, fns...)
	return aps
}

// Scan applies the selector query and scans the result into the given value.
func (aps *ArticlePurchaseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aps.ctx, ent.OpQuerySelect)
	if err := aps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ArticlePurchaseQuery, *ArticlePurchaseSelect](ctx, aps.ArticlePurchaseQuery, aps, aps.inters, v)
}

func (aps *ArticlePurchaseSelect) sqlScan(ctx context.Context, root *ArticlePurchaseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aps.fns))
	for _, fn := range aps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (aps *ArticlePurchaseSelect) Modify(modifiers ...func(s *sql.Selector)) *ArticlePurchaseSelect {
	aps.modifiers = append(aps.modifiers, modifiers...)
	return aps
}
