// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/articlepayment"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ArticlePaymentDelete is the builder for deleting a ArticlePayment entity.
type ArticlePaymentDelete struct {
	config
	hooks    []Hook
	mutation *ArticlePaymentMutation
}

// Where appends a list predicates to the ArticlePaymentDelete builder.
func (apd *ArticlePaymentDelete) Where(ps ...predicate.ArticlePayment) *ArticlePaymentDelete {
	apd.mutation.Where(ps...)
	return apd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (apd *ArticlePaymentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, apd.sqlExec, apd.mutation, apd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (apd *ArticlePaymentDelete) ExecX(ctx context.Context) int {
	n, err := apd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (apd *ArticlePaymentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(articlepayment.Table, sqlgraph.NewFieldSpec(articlepayment.FieldID, field.TypeUint))
	if ps := apd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, apd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	apd.mutation.done = true
	return affected, err
}

// ArticlePaymentDeleteOne is the builder for deleting a single ArticlePayment entity.
type ArticlePaymentDeleteOne struct {
	apd *ArticlePaymentDelete
}

// Where appends a list predicates to the ArticlePaymentDelete builder.
func (apdo *ArticlePaymentDeleteOne) Where(ps ...predicate.ArticlePayment) *ArticlePaymentDeleteOne {
	apdo.apd.mutation.Where(ps...)
	return apdo
}

// Exec executes the deletion query.
func (apdo *ArticlePaymentDeleteOne) Exec(ctx context.Context) error {
	n, err := apdo.apd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{articlepayment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (apdo *ArticlePaymentDeleteOne) ExecX(ctx context.Context) {
	if err := apdo.Exec(ctx); err != nil {
		panic(err)
	}
}
