// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/articlepurchase"
)

// 文章付费购买记录表
type ArticlePurchase struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// 支付系统用户ID
	UserID string `json:"user_id,omitempty"`
	// 文章ID
	ArticleID uint `json:"article_id,omitempty"`
	// 付费内容块ID
	BlockID string `json:"block_id,omitempty"`
	// 购买价格，单位为分
	Price int `json:"price,omitempty"`
	// 订单号
	OrderNo *string `json:"order_no,omitempty"`
	// 购买时间
	PurchasedAt  time.Time `json:"purchased_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArticlePurchase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case articlepurchase.FieldID, articlepurchase.FieldArticleID, articlepurchase.FieldPrice:
			values[i] = new(sql.NullInt64)
		case articlepurchase.FieldUserID, articlepurchase.FieldBlockID, articlepurchase.FieldOrderNo:
			values[i] = new(sql.NullString)
		case articlepurchase.FieldPurchasedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArticlePurchase fields.
func (ap *ArticlePurchase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case articlepurchase.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ap.ID = uint(value.Int64)
		case articlepurchase.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ap.UserID = value.String
			}
		case articlepurchase.FieldArticleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field article_id", values[i])
			} else if value.Valid {
				ap.ArticleID = uint(value.Int64)
			}
		case articlepurchase.FieldBlockID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field block_id", values[i])
			} else if value.Valid {
				ap.BlockID = value.String
			}
		case articlepurchase.FieldPrice:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				ap.Price = int(value.Int64)
			}
		case articlepurchase.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				ap.OrderNo = new(string)
				*ap.OrderNo = value.String
			}
		case articlepurchase.FieldPurchasedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field purchased_at", values[i])
			} else if value.Valid {
				ap.PurchasedAt = value.Time
			}
		default:
			ap.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ArticlePurchase.
// This includes values selected through modifiers, order, etc.
func (ap *ArticlePurchase) Value(name string) (ent.Value, error) {
	return ap.selectValues.Get(name)
}

// Update returns a builder for updating this ArticlePurchase.
// Note that you need to call ArticlePurchase.Unwrap() before calling this method if this ArticlePurchase
// was returned from a transaction, and the transaction was committed or rolled back.
func (ap *ArticlePurchase) Update() *ArticlePurchaseUpdateOne {
	return NewArticlePurchaseClient(ap.config).UpdateOne(ap)
}

// Unwrap unwraps the ArticlePurchase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ap *ArticlePurchase) Unwrap() *ArticlePurchase {
	_tx, ok := ap.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArticlePurchase is not a transactional entity")
	}
	ap.config.driver = _tx.drv
	return ap
}

// String implements the fmt.Stringer.
func (ap *ArticlePurchase) String() string {
	var builder strings.Builder
	builder.WriteString("ArticlePurchase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ap.ID))
	builder.WriteString("user_id=")
	builder.WriteString(ap.UserID)
	builder.WriteString(", ")
	builder.WriteString("article_id=")
	builder.WriteString(fmt.Sprintf("%v", ap.ArticleID))
	builder.WriteString(", ")
	builder.WriteString("block_id=")
	builder.WriteString(ap.BlockID)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", ap.Price))
	builder.WriteString(", ")
	if v := ap.OrderNo; v != nil {
		builder.WriteString("order_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("purchased_at=")
	builder.WriteString(ap.PurchasedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ArticlePurchases is a parsable slice of ArticlePurchase.
type ArticlePurchases []*ArticlePurchase
