// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/articlepayment"
)

// 文章付费内容块表
type ArticlePayment struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// 关联文章ID
	ArticleID uint `json:"article_id,omitempty"`
	// 付费内容块唯一标识
	BlockID string `json:"block_id,omitempty"`
	// 付费内容块标题
	Title string `json:"title,omitempty"`
	// 价格，单位为分
	Price int `json:"price,omitempty"`
	// 原价，单位为分
	OriginalPrice *int `json:"original_price,omitempty"`
	// 货币符号
	Currency string `json:"currency,omitempty"`
	// 内容字数
	ContentLength int `json:"content_length,omitempty"`
	// 会员是否也需要单独购买
	ExcludeFromMembership bool `json:"exclude_from_membership,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArticlePayment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case articlepayment.FieldExcludeFromMembership:
			values[i] = new(sql.NullBool)
		case articlepayment.FieldID, articlepayment.FieldArticleID, articlepayment.FieldPrice, articlepayment.FieldOriginalPrice, articlepayment.FieldContentLength:
			values[i] = new(sql.NullInt64)
		case articlepayment.FieldBlockID, articlepayment.FieldTitle, articlepayment.FieldCurrency:
			values[i] = new(sql.NullString)
		case articlepayment.FieldCreatedAt, articlepayment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArticlePayment fields.
func (ap *ArticlePayment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case articlepayment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ap.ID = uint(value.Int64)
		case articlepayment.FieldArticleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field article_id", values[i])
			} else if value.Valid {
				ap.ArticleID = uint(value.Int64)
			}
		case articlepayment.FieldBlockID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field block_id", values[i])
			} else if value.Valid {
				ap.BlockID = value.String
			}
		case articlepayment.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				ap.Title = value.String
			}
		case articlepayment.FieldPrice:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				ap.Price = int(value.Int64)
			}
		case articlepayment.FieldOriginalPrice:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field original_price", values[i])
			} else if value.Valid {
				ap.OriginalPrice = new(int)
				*ap.OriginalPrice = int(value.Int64)
			}
		case articlepayment.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				ap.Currency = value.String
			}
		case articlepayment.FieldContentLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field content_length", values[i])
			} else if value.Valid {
				ap.ContentLength = int(value.Int64)
			}
		case articlepayment.FieldExcludeFromMembership:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field exclude_from_membership", values[i])
			} else if value.Valid {
				ap.ExcludeFromMembership = value.Bool
			}
		case articlepayment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ap.CreatedAt = value.Time
			}
		case articlepayment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ap.UpdatedAt = value.Time
			}
		default:
			ap.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ArticlePayment.
// This includes values selected through modifiers, order, etc.
func (ap *ArticlePayment) Value(name string) (ent.Value, error) {
	return ap.selectValues.Get(name)
}

// Update returns a builder for updating this ArticlePayment.
// Note that you need to call ArticlePayment.Unwrap() before calling this method if this ArticlePayment
// was returned from a transaction, and the transaction was committed or rolled back.
func (ap *ArticlePayment) Update() *ArticlePaymentUpdateOne {
	return NewArticlePaymentClient(ap.config).UpdateOne(ap)
}

// Unwrap unwraps the ArticlePayment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ap *ArticlePayment) Unwrap() *ArticlePayment {
	_tx, ok := ap.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArticlePayment is not a transactional entity")
	}
	ap.config.driver = _tx.drv
	return ap
}

// String implements the fmt.Stringer.
func (ap *ArticlePayment) String() string {
	var builder strings.Builder
	builder.WriteString("ArticlePayment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ap.ID))
	builder.WriteString("article_id=")
	builder.WriteString(fmt.Sprintf("%v", ap.ArticleID))
	builder.WriteString(", ")
	builder.WriteString("block_id=")
	builder.WriteString(ap.BlockID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(ap.Title)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", ap.Price))
	builder.WriteString(", ")
	if v := ap.OriginalPrice; v != nil {
		builder.WriteString("original_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(ap.Currency)
	builder.WriteString(", ")
	builder.WriteString("content_length=")
	builder.WriteString(fmt.Sprintf("%v", ap.ContentLength))
	builder.WriteString(", ")
	builder.WriteString("exclude_from_membership=")
	builder.WriteString(fmt.Sprintf("%v", ap.ExcludeFromMembership))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ap.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ap.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ArticlePayments is a parsable slice of ArticlePayment.
type ArticlePayments []*ArticlePayment
