// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/memberbinding"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// MemberBindingUpdate is the builder for updating MemberBinding entities.
type MemberBindingUpdate struct {
	config
	hooks     []Hook
	mutation  *MemberBindingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MemberBindingUpdate builder.
func (_u *MemberBindingUpdate) Where(ps ...predicate.MemberBinding) *MemberBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MemberBindingUpdate) SetUserID(v int64) *MemberBindingUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemberBindingUpdate) SetNillableUserID(v *int64) *MemberBindingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MemberBindingUpdate) AddUserID(v int64) *MemberBindingUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetExternalUserID sets the "external_user_id" field.
func (_u *MemberBindingUpdate) SetExternalUserID(v string) *MemberBindingUpdate {
	_u.mutation.SetExternalUserID(v)
	return _u
}

// SetNillableExternalUserID sets the "external_user_id" field if the given value is not nil.
func (_u *MemberBindingUpdate) SetNillableExternalUserID(v *string) *MemberBindingUpdate {
	if v != nil {
		_u.SetExternalUserID(*v)
	}
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *MemberBindingUpdate) SetSiteID(v string) *MemberBindingUpdate {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *MemberBindingUpdate) SetNillableSiteID(v *string) *MemberBindingUpdate {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MemberBindingUpdate) SetStatus(v string) *MemberBindingUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MemberBindingUpdate) SetNillableStatus(v *string) *MemberBindingUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *MemberBindingUpdate) SetLastSyncedAt(v time.Time) *MemberBindingUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *MemberBindingUpdate) SetNillableLastSyncedAt(v *time.Time) *MemberBindingUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *MemberBindingUpdate) ClearLastSyncedAt() *MemberBindingUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberBindingUpdate) SetUpdatedAt(v time.Time) *MemberBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MemberBindingMutation object of the builder.
func (_u *MemberBindingUpdate) Mutation() *MemberBindingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memberbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberBindingUpdate) check() error {
	if v, ok := _u.mutation.ExternalUserID(); ok {
		if err := memberbinding.ExternalUserIDValidator(v); err != nil {
			return &ValidationError{Name: "external_user_id", err: fmt.Errorf(`ent: validator failed for field "MemberBinding.external_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteID(); ok {
		if err := memberbinding.SiteIDValidator(v); err != nil {
			return &ValidationError{Name: "site_id", err: fmt.Errorf(`ent: validator failed for field "MemberBinding.site_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MemberBindingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MemberBindingUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MemberBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberbinding.Table, memberbinding.Columns, sqlgraph.NewFieldSpec(memberbinding.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(memberbinding.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(memberbinding.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExternalUserID(); ok {
		_spec.SetField(memberbinding.FieldExternalUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteID(); ok {
		_spec.SetField(memberbinding.FieldSiteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(memberbinding.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(memberbinding.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(memberbinding.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memberbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberBindingUpdateOne is the builder for updating a single MemberBinding entity.
type MemberBindingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MemberBindingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *MemberBindingUpdateOne) SetUserID(v int64) *MemberBindingUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemberBindingUpdateOne) SetNillableUserID(v *int64) *MemberBindingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MemberBindingUpdateOne) AddUserID(v int64) *MemberBindingUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetExternalUserID sets the "external_user_id" field.
func (_u *MemberBindingUpdateOne) SetExternalUserID(v string) *MemberBindingUpdateOne {
	_u.mutation.SetExternalUserID(v)
	return _u
}

// SetNillableExternalUserID sets the "external_user_id" field if the given value is not nil.
func (_u *MemberBindingUpdateOne) SetNillableExternalUserID(v *string) *MemberBindingUpdateOne {
	if v != nil {
		_u.SetExternalUserID(*v)
	}
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *MemberBindingUpdateOne) SetSiteID(v string) *MemberBindingUpdateOne {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *MemberBindingUpdateOne) SetNillableSiteID(v *string) *MemberBindingUpdateOne {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MemberBindingUpdateOne) SetStatus(v string) *MemberBindingUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MemberBindingUpdateOne) SetNillableStatus(v *string) *MemberBindingUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *MemberBindingUpdateOne) SetLastSyncedAt(v time.Time) *MemberBindingUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *MemberBindingUpdateOne) SetNillableLastSyncedAt(v *time.Time) *MemberBindingUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *MemberBindingUpdateOne) ClearLastSyncedAt() *MemberBindingUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberBindingUpdateOne) SetUpdatedAt(v time.Time) *MemberBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MemberBindingMutation object of the builder.
func (_u *MemberBindingUpdateOne) Mutation() *MemberBindingMutation {
	return _u.mutation
}

// Where appends a list predicates to the MemberBindingUpdate builder.
func (_u *MemberBindingUpdateOne) Where(ps ...predicate.MemberBinding) *MemberBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberBindingUpdateOne) Select(field string, fields ...string) *MemberBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemberBinding entity.
func (_u *MemberBindingUpdateOne) Save(ctx context.Context) (*MemberBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberBindingUpdateOne) SaveX(ctx context.Context) *MemberBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memberbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberBindingUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalUserID(); ok {
		if err := memberbinding.ExternalUserIDValidator(v); err != nil {
			return &ValidationError{Name: "external_user_id", err: fmt.Errorf(`ent: validator failed for field "MemberBinding.external_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteID(); ok {
		if err := memberbinding.SiteIDValidator(v); err != nil {
			return &ValidationError{Name: "site_id", err: fmt.Errorf(`ent: validator failed for field "MemberBinding.site_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MemberBindingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MemberBindingUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MemberBindingUpdateOne) sqlSave(ctx context.Context) (_node *MemberBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberbinding.Table, memberbinding.Columns, sqlgraph.NewFieldSpec(memberbinding.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberbinding.FieldID)
		for _, f := range fields {
			if !memberbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memberbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(memberbinding.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(memberbinding.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExternalUserID(); ok {
		_spec.SetField(memberbinding.FieldExternalUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteID(); ok {
		_spec.SetField(memberbinding.FieldSiteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(memberbinding.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(memberbinding.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(memberbinding.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memberbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MemberBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
