// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/memberzonecontent"
)

// 会员专区内容表
type MemberZoneContent struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 内容标题
	Title string `json:"title,omitempty"`
	// 内容短链
	Slug string `json:"slug,omitempty"`
	// 内容摘要
	Summary string `json:"summary,omitempty"`
	// 封面图 URL
	CoverURL string `json:"cover_url,omitempty"`
	// Markdown 原文
	ContentMd string `json:"content_md,omitempty"`
	// 渲染后的 HTML
	ContentHTML string `json:"content_html,omitempty"`
	// 状态：draft/published/archived
	Status string `json:"status,omitempty"`
	// 访问等级：member/premium
	AccessLevel string `json:"access_level,omitempty"`
	// 排序值，越小越靠前
	Sort int `json:"sort,omitempty"`
	// 关联文章公共 ID
	SourceArticleID *string `json:"source_article_id,omitempty"`
	// 发布时间
	PublishedAt  *time.Time `json:"published_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberZoneContent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memberzonecontent.FieldID, memberzonecontent.FieldSort:
			values[i] = new(sql.NullInt64)
		case memberzonecontent.FieldTitle, memberzonecontent.FieldSlug, memberzonecontent.FieldSummary, memberzonecontent.FieldCoverURL, memberzonecontent.FieldContentMd, memberzonecontent.FieldContentHTML, memberzonecontent.FieldStatus, memberzonecontent.FieldAccessLevel, memberzonecontent.FieldSourceArticleID:
			values[i] = new(sql.NullString)
		case memberzonecontent.FieldDeletedAt, memberzonecontent.FieldCreatedAt, memberzonecontent.FieldUpdatedAt, memberzonecontent.FieldPublishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberZoneContent fields.
func (_m *MemberZoneContent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memberzonecontent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case memberzonecontent.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case memberzonecontent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case memberzonecontent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case memberzonecontent.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case memberzonecontent.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case memberzonecontent.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case memberzonecontent.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				_m.CoverURL = value.String
			}
		case memberzonecontent.FieldContentMd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_md", values[i])
			} else if value.Valid {
				_m.ContentMd = value.String
			}
		case memberzonecontent.FieldContentHTML:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_html", values[i])
			} else if value.Valid {
				_m.ContentHTML = value.String
			}
		case memberzonecontent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case memberzonecontent.FieldAccessLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_level", values[i])
			} else if value.Valid {
				_m.AccessLevel = value.String
			}
		case memberzonecontent.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		case memberzonecontent.FieldSourceArticleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_article_id", values[i])
			} else if value.Valid {
				_m.SourceArticleID = new(string)
				*_m.SourceArticleID = value.String
			}
		case memberzonecontent.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberZoneContent.
// This includes values selected through modifiers, order, etc.
func (_m *MemberZoneContent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MemberZoneContent.
// Note that you need to call MemberZoneContent.Unwrap() before calling this method if this MemberZoneContent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemberZoneContent) Update() *MemberZoneContentUpdateOne {
	return NewMemberZoneContentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemberZoneContent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemberZoneContent) Unwrap() *MemberZoneContent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberZoneContent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemberZoneContent) String() string {
	var builder strings.Builder
	builder.WriteString("MemberZoneContent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("cover_url=")
	builder.WriteString(_m.CoverURL)
	builder.WriteString(", ")
	builder.WriteString("content_md=")
	builder.WriteString(_m.ContentMd)
	builder.WriteString(", ")
	builder.WriteString("content_html=")
	builder.WriteString(_m.ContentHTML)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("access_level=")
	builder.WriteString(_m.AccessLevel)
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	if v := _m.SourceArticleID; v != nil {
		builder.WriteString("source_article_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MemberZoneContents is a parsable slice of MemberZoneContent.
type MemberZoneContents []*MemberZoneContent
