// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/memberzonecontent"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// MemberZoneContentUpdate is the builder for updating MemberZoneContent entities.
type MemberZoneContentUpdate struct {
	config
	hooks     []Hook
	mutation  *MemberZoneContentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MemberZoneContentUpdate builder.
func (_u *MemberZoneContentUpdate) Where(ps ...predicate.MemberZoneContent) *MemberZoneContentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MemberZoneContentUpdate) SetDeletedAt(v time.Time) *MemberZoneContentUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableDeletedAt(v *time.Time) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MemberZoneContentUpdate) ClearDeletedAt() *MemberZoneContentUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberZoneContentUpdate) SetUpdatedAt(v time.Time) *MemberZoneContentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MemberZoneContentUpdate) SetTitle(v string) *MemberZoneContentUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableTitle(v *string) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *MemberZoneContentUpdate) SetSlug(v string) *MemberZoneContentUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableSlug(v *string) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *MemberZoneContentUpdate) SetSummary(v string) *MemberZoneContentUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableSummary(v *string) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *MemberZoneContentUpdate) ClearSummary() *MemberZoneContentUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *MemberZoneContentUpdate) SetCoverURL(v string) *MemberZoneContentUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableCoverURL(v *string) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *MemberZoneContentUpdate) ClearCoverURL() *MemberZoneContentUpdate {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetContentMd sets the "content_md" field.
func (_u *MemberZoneContentUpdate) SetContentMd(v string) *MemberZoneContentUpdate {
	_u.mutation.SetContentMd(v)
	return _u
}

// SetNillableContentMd sets the "content_md" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableContentMd(v *string) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetContentMd(*v)
	}
	return _u
}

// SetContentHTML sets the "content_html" field.
func (_u *MemberZoneContentUpdate) SetContentHTML(v string) *MemberZoneContentUpdate {
	_u.mutation.SetContentHTML(v)
	return _u
}

// SetNillableContentHTML sets the "content_html" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableContentHTML(v *string) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetContentHTML(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MemberZoneContentUpdate) SetStatus(v string) *MemberZoneContentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableStatus(v *string) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAccessLevel sets the "access_level" field.
func (_u *MemberZoneContentUpdate) SetAccessLevel(v string) *MemberZoneContentUpdate {
	_u.mutation.SetAccessLevel(v)
	return _u
}

// SetNillableAccessLevel sets the "access_level" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableAccessLevel(v *string) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetAccessLevel(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *MemberZoneContentUpdate) SetSort(v int) *MemberZoneContentUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableSort(v *int) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *MemberZoneContentUpdate) AddSort(v int) *MemberZoneContentUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetSourceArticleID sets the "source_article_id" field.
func (_u *MemberZoneContentUpdate) SetSourceArticleID(v string) *MemberZoneContentUpdate {
	_u.mutation.SetSourceArticleID(v)
	return _u
}

// SetNillableSourceArticleID sets the "source_article_id" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillableSourceArticleID(v *string) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetSourceArticleID(*v)
	}
	return _u
}

// ClearSourceArticleID clears the value of the "source_article_id" field.
func (_u *MemberZoneContentUpdate) ClearSourceArticleID() *MemberZoneContentUpdate {
	_u.mutation.ClearSourceArticleID()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *MemberZoneContentUpdate) SetPublishedAt(v time.Time) *MemberZoneContentUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *MemberZoneContentUpdate) SetNillablePublishedAt(v *time.Time) *MemberZoneContentUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *MemberZoneContentUpdate) ClearPublishedAt() *MemberZoneContentUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the MemberZoneContentMutation object of the builder.
func (_u *MemberZoneContentUpdate) Mutation() *MemberZoneContentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberZoneContentUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberZoneContentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberZoneContentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberZoneContentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberZoneContentUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if memberzonecontent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized memberzonecontent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := memberzonecontent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberZoneContentUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := memberzonecontent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := memberzonecontent.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := memberzonecontent.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := memberzonecontent.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := memberzonecontent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessLevel(); ok {
		if err := memberzonecontent.AccessLevelValidator(v); err != nil {
			return &ValidationError{Name: "access_level", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.access_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceArticleID(); ok {
		if err := memberzonecontent.SourceArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "source_article_id", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.source_article_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MemberZoneContentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MemberZoneContentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MemberZoneContentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberzonecontent.Table, memberzonecontent.Columns, sqlgraph.NewFieldSpec(memberzonecontent.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(memberzonecontent.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(memberzonecontent.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memberzonecontent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(memberzonecontent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(memberzonecontent.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(memberzonecontent.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(memberzonecontent.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(memberzonecontent.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(memberzonecontent.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.ContentMd(); ok {
		_spec.SetField(memberzonecontent.FieldContentMd, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHTML(); ok {
		_spec.SetField(memberzonecontent.FieldContentHTML, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(memberzonecontent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessLevel(); ok {
		_spec.SetField(memberzonecontent.FieldAccessLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(memberzonecontent.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(memberzonecontent.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceArticleID(); ok {
		_spec.SetField(memberzonecontent.FieldSourceArticleID, field.TypeString, value)
	}
	if _u.mutation.SourceArticleIDCleared() {
		_spec.ClearField(memberzonecontent.FieldSourceArticleID, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(memberzonecontent.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(memberzonecontent.FieldPublishedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberzonecontent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberZoneContentUpdateOne is the builder for updating a single MemberZoneContent entity.
type MemberZoneContentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MemberZoneContentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MemberZoneContentUpdateOne) SetDeletedAt(v time.Time) *MemberZoneContentUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableDeletedAt(v *time.Time) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MemberZoneContentUpdateOne) ClearDeletedAt() *MemberZoneContentUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberZoneContentUpdateOne) SetUpdatedAt(v time.Time) *MemberZoneContentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MemberZoneContentUpdateOne) SetTitle(v string) *MemberZoneContentUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableTitle(v *string) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *MemberZoneContentUpdateOne) SetSlug(v string) *MemberZoneContentUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableSlug(v *string) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *MemberZoneContentUpdateOne) SetSummary(v string) *MemberZoneContentUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableSummary(v *string) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *MemberZoneContentUpdateOne) ClearSummary() *MemberZoneContentUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *MemberZoneContentUpdateOne) SetCoverURL(v string) *MemberZoneContentUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableCoverURL(v *string) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *MemberZoneContentUpdateOne) ClearCoverURL() *MemberZoneContentUpdateOne {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetContentMd sets the "content_md" field.
func (_u *MemberZoneContentUpdateOne) SetContentMd(v string) *MemberZoneContentUpdateOne {
	_u.mutation.SetContentMd(v)
	return _u
}

// SetNillableContentMd sets the "content_md" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableContentMd(v *string) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetContentMd(*v)
	}
	return _u
}

// SetContentHTML sets the "content_html" field.
func (_u *MemberZoneContentUpdateOne) SetContentHTML(v string) *MemberZoneContentUpdateOne {
	_u.mutation.SetContentHTML(v)
	return _u
}

// SetNillableContentHTML sets the "content_html" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableContentHTML(v *string) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetContentHTML(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MemberZoneContentUpdateOne) SetStatus(v string) *MemberZoneContentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableStatus(v *string) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAccessLevel sets the "access_level" field.
func (_u *MemberZoneContentUpdateOne) SetAccessLevel(v string) *MemberZoneContentUpdateOne {
	_u.mutation.SetAccessLevel(v)
	return _u
}

// SetNillableAccessLevel sets the "access_level" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableAccessLevel(v *string) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetAccessLevel(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *MemberZoneContentUpdateOne) SetSort(v int) *MemberZoneContentUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableSort(v *int) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *MemberZoneContentUpdateOne) AddSort(v int) *MemberZoneContentUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetSourceArticleID sets the "source_article_id" field.
func (_u *MemberZoneContentUpdateOne) SetSourceArticleID(v string) *MemberZoneContentUpdateOne {
	_u.mutation.SetSourceArticleID(v)
	return _u
}

// SetNillableSourceArticleID sets the "source_article_id" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillableSourceArticleID(v *string) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetSourceArticleID(*v)
	}
	return _u
}

// ClearSourceArticleID clears the value of the "source_article_id" field.
func (_u *MemberZoneContentUpdateOne) ClearSourceArticleID() *MemberZoneContentUpdateOne {
	_u.mutation.ClearSourceArticleID()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *MemberZoneContentUpdateOne) SetPublishedAt(v time.Time) *MemberZoneContentUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *MemberZoneContentUpdateOne) SetNillablePublishedAt(v *time.Time) *MemberZoneContentUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *MemberZoneContentUpdateOne) ClearPublishedAt() *MemberZoneContentUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the MemberZoneContentMutation object of the builder.
func (_u *MemberZoneContentUpdateOne) Mutation() *MemberZoneContentMutation {
	return _u.mutation
}

// Where appends a list predicates to the MemberZoneContentUpdate builder.
func (_u *MemberZoneContentUpdateOne) Where(ps ...predicate.MemberZoneContent) *MemberZoneContentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberZoneContentUpdateOne) Select(field string, fields ...string) *MemberZoneContentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemberZoneContent entity.
func (_u *MemberZoneContentUpdateOne) Save(ctx context.Context) (*MemberZoneContent, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberZoneContentUpdateOne) SaveX(ctx context.Context) *MemberZoneContent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberZoneContentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberZoneContentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberZoneContentUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if memberzonecontent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized memberzonecontent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := memberzonecontent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberZoneContentUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := memberzonecontent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := memberzonecontent.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := memberzonecontent.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := memberzonecontent.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := memberzonecontent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessLevel(); ok {
		if err := memberzonecontent.AccessLevelValidator(v); err != nil {
			return &ValidationError{Name: "access_level", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.access_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceArticleID(); ok {
		if err := memberzonecontent.SourceArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "source_article_id", err: fmt.Errorf(`ent: validator failed for field "MemberZoneContent.source_article_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MemberZoneContentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MemberZoneContentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MemberZoneContentUpdateOne) sqlSave(ctx context.Context) (_node *MemberZoneContent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberzonecontent.Table, memberzonecontent.Columns, sqlgraph.NewFieldSpec(memberzonecontent.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberZoneContent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberzonecontent.FieldID)
		for _, f := range fields {
			if !memberzonecontent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memberzonecontent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(memberzonecontent.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(memberzonecontent.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memberzonecontent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(memberzonecontent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(memberzonecontent.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(memberzonecontent.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(memberzonecontent.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(memberzonecontent.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(memberzonecontent.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.ContentMd(); ok {
		_spec.SetField(memberzonecontent.FieldContentMd, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHTML(); ok {
		_spec.SetField(memberzonecontent.FieldContentHTML, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(memberzonecontent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessLevel(); ok {
		_spec.SetField(memberzonecontent.FieldAccessLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(memberzonecontent.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(memberzonecontent.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceArticleID(); ok {
		_spec.SetField(memberzonecontent.FieldSourceArticleID, field.TypeString, value)
	}
	if _u.mutation.SourceArticleIDCleared() {
		_spec.ClearField(memberzonecontent.FieldSourceArticleID, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(memberzonecontent.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(memberzonecontent.FieldPublishedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MemberZoneContent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberzonecontent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
