// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/resource"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceitem"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceorder"
)

// ResourceOrderCreate is the builder for creating a ResourceOrder entity.
type ResourceOrderCreate struct {
	config
	mutation *ResourceOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceOrderCreate) SetCreatedAt(v time.Time) *ResourceOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceOrderCreate) SetNillableCreatedAt(v *time.Time) *ResourceOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResourceOrderCreate) SetUpdatedAt(v time.Time) *ResourceOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResourceOrderCreate) SetNillableUpdatedAt(v *time.Time) *ResourceOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ResourceOrderCreate) SetUserID(v int64) *ResourceOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *ResourceOrderCreate) SetResourceID(v uint) *ResourceOrderCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetResourceItemID sets the "resource_item_id" field.
func (_c *ResourceOrderCreate) SetResourceItemID(v uint) *ResourceOrderCreate {
	_c.mutation.SetResourceItemID(v)
	return _c
}

// SetNillableResourceItemID sets the "resource_item_id" field if the given value is not nil.
func (_c *ResourceOrderCreate) SetNillableResourceItemID(v *uint) *ResourceOrderCreate {
	if v != nil {
		_c.SetResourceItemID(*v)
	}
	return _c
}

// SetBusinessOrderNo sets the "business_order_no" field.
func (_c *ResourceOrderCreate) SetBusinessOrderNo(v string) *ResourceOrderCreate {
	_c.mutation.SetBusinessOrderNo(v)
	return _c
}

// SetExternalOrderNo sets the "external_order_no" field.
func (_c *ResourceOrderCreate) SetExternalOrderNo(v string) *ResourceOrderCreate {
	_c.mutation.SetExternalOrderNo(v)
	return _c
}

// SetNillableExternalOrderNo sets the "external_order_no" field if the given value is not nil.
func (_c *ResourceOrderCreate) SetNillableExternalOrderNo(v *string) *ResourceOrderCreate {
	if v != nil {
		_c.SetExternalOrderNo(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ResourceOrderCreate) SetAmount(v float64) *ResourceOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ResourceOrderCreate) SetNillableAmount(v *float64) *ResourceOrderCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResourceOrderCreate) SetStatus(v string) *ResourceOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ResourceOrderCreate) SetNillableStatus(v *string) *ResourceOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSnapshot sets the "snapshot" field.
func (_c *ResourceOrderCreate) SetSnapshot(v map[string]interface{}) *ResourceOrderCreate {
	_c.mutation.SetSnapshot(v)
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *ResourceOrderCreate) SetPaidAt(v time.Time) *ResourceOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *ResourceOrderCreate) SetNillablePaidAt(v *time.Time) *ResourceOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ResourceOrderCreate) SetID(v uint) *ResourceOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetResource sets the "resource" edge to the Resource entity.
func (_c *ResourceOrderCreate) SetResource(v *Resource) *ResourceOrderCreate {
	return _c.SetResourceID(v.ID)
}

// SetResourceItem sets the "resource_item" edge to the ResourceItem entity.
func (_c *ResourceOrderCreate) SetResourceItem(v *ResourceItem) *ResourceOrderCreate {
	return _c.SetResourceItemID(v.ID)
}

// Mutation returns the ResourceOrderMutation object of the builder.
func (_c *ResourceOrderCreate) Mutation() *ResourceOrderMutation {
	return _c.mutation
}

// Save creates the ResourceOrder in the database.
func (_c *ResourceOrderCreate) Save(ctx context.Context) (*ResourceOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceOrderCreate) SaveX(ctx context.Context) *ResourceOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resourceorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resourceorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := resourceorder.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := resourceorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResourceOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResourceOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ResourceOrder.user_id"`)}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "ResourceOrder.resource_id"`)}
	}
	if _, ok := _c.mutation.BusinessOrderNo(); !ok {
		return &ValidationError{Name: "business_order_no", err: errors.New(`ent: missing required field "ResourceOrder.business_order_no"`)}
	}
	if v, ok := _c.mutation.BusinessOrderNo(); ok {
		if err := resourceorder.BusinessOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "business_order_no", err: fmt.Errorf(`ent: validator failed for field "ResourceOrder.business_order_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExternalOrderNo(); ok {
		if err := resourceorder.ExternalOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "external_order_no", err: fmt.Errorf(`ent: validator failed for field "ResourceOrder.external_order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ResourceOrder.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ResourceOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := resourceorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResourceOrder.status": %w`, err)}
		}
	}
	if len(_c.mutation.ResourceIDs()) == 0 {
		return &ValidationError{Name: "resource", err: errors.New(`ent: missing required edge "ResourceOrder.resource"`)}
	}
	return nil
}

func (_c *ResourceOrderCreate) sqlSave(ctx context.Context) (*ResourceOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceOrderCreate) createSpec() (*ResourceOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &ResourceOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resourceorder.Table, sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resourceorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resourceorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(resourceorder.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.BusinessOrderNo(); ok {
		_spec.SetField(resourceorder.FieldBusinessOrderNo, field.TypeString, value)
		_node.BusinessOrderNo = value
	}
	if value, ok := _c.mutation.ExternalOrderNo(); ok {
		_spec.SetField(resourceorder.FieldExternalOrderNo, field.TypeString, value)
		_node.ExternalOrderNo = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(resourceorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(resourceorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Snapshot(); ok {
		_spec.SetField(resourceorder.FieldSnapshot, field.TypeJSON, value)
		_node.Snapshot = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(resourceorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if nodes := _c.mutation.ResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceorder.ResourceTable,
			Columns: []string{resourceorder.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ResourceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ResourceItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceorder.ResourceItemTable,
			Columns: []string{resourceorder.ResourceItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ResourceItemID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceOrderCreate) OnConflict(opts ...sql.ConflictOption) *ResourceOrderUpsertOne {
	_c.conflict = opts
	return &ResourceOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceOrderCreate) OnConflictColumns(columns ...string) *ResourceOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceOrderUpsertOne{
		create: _c,
	}
}

type (
	// ResourceOrderUpsertOne is the builder for "upsert"-ing
	//  one ResourceOrder node.
	ResourceOrderUpsertOne struct {
		create *ResourceOrderCreate
	}

	// ResourceOrderUpsert is the "OnConflict" setter.
	ResourceOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceOrderUpsert) SetUpdatedAt(v time.Time) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdateUpdatedAt() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ResourceOrderUpsert) SetUserID(v int64) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdateUserID() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ResourceOrderUpsert) AddUserID(v int64) *ResourceOrderUpsert {
	u.Add(resourceorder.FieldUserID, v)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *ResourceOrderUpsert) SetResourceID(v uint) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdateResourceID() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldResourceID)
	return u
}

// SetResourceItemID sets the "resource_item_id" field.
func (u *ResourceOrderUpsert) SetResourceItemID(v uint) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldResourceItemID, v)
	return u
}

// UpdateResourceItemID sets the "resource_item_id" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdateResourceItemID() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldResourceItemID)
	return u
}

// ClearResourceItemID clears the value of the "resource_item_id" field.
func (u *ResourceOrderUpsert) ClearResourceItemID() *ResourceOrderUpsert {
	u.SetNull(resourceorder.FieldResourceItemID)
	return u
}

// SetBusinessOrderNo sets the "business_order_no" field.
func (u *ResourceOrderUpsert) SetBusinessOrderNo(v string) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldBusinessOrderNo, v)
	return u
}

// UpdateBusinessOrderNo sets the "business_order_no" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdateBusinessOrderNo() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldBusinessOrderNo)
	return u
}

// SetExternalOrderNo sets the "external_order_no" field.
func (u *ResourceOrderUpsert) SetExternalOrderNo(v string) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldExternalOrderNo, v)
	return u
}

// UpdateExternalOrderNo sets the "external_order_no" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdateExternalOrderNo() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldExternalOrderNo)
	return u
}

// ClearExternalOrderNo clears the value of the "external_order_no" field.
func (u *ResourceOrderUpsert) ClearExternalOrderNo() *ResourceOrderUpsert {
	u.SetNull(resourceorder.FieldExternalOrderNo)
	return u
}

// SetAmount sets the "amount" field.
func (u *ResourceOrderUpsert) SetAmount(v float64) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdateAmount() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ResourceOrderUpsert) AddAmount(v float64) *ResourceOrderUpsert {
	u.Add(resourceorder.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ResourceOrderUpsert) SetStatus(v string) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdateStatus() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldStatus)
	return u
}

// SetSnapshot sets the "snapshot" field.
func (u *ResourceOrderUpsert) SetSnapshot(v map[string]interface{}) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldSnapshot, v)
	return u
}

// UpdateSnapshot sets the "snapshot" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdateSnapshot() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldSnapshot)
	return u
}

// ClearSnapshot clears the value of the "snapshot" field.
func (u *ResourceOrderUpsert) ClearSnapshot() *ResourceOrderUpsert {
	u.SetNull(resourceorder.FieldSnapshot)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *ResourceOrderUpsert) SetPaidAt(v time.Time) *ResourceOrderUpsert {
	u.Set(resourceorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *ResourceOrderUpsert) UpdatePaidAt() *ResourceOrderUpsert {
	u.SetExcluded(resourceorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *ResourceOrderUpsert) ClearPaidAt() *ResourceOrderUpsert {
	u.SetNull(resourceorder.FieldPaidAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ResourceOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resourceorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResourceOrderUpsertOne) UpdateNewValues() *ResourceOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(resourceorder.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resourceorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResourceOrderUpsertOne) Ignore() *ResourceOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceOrderUpsertOne) DoNothing() *ResourceOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceOrderCreate.OnConflict
// documentation for more info.
func (u *ResourceOrderUpsertOne) Update(set func(*ResourceOrderUpsert)) *ResourceOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceOrderUpsertOne) SetUpdatedAt(v time.Time) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdateUpdatedAt() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResourceOrderUpsertOne) SetUserID(v int64) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResourceOrderUpsertOne) AddUserID(v int64) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdateUserID() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *ResourceOrderUpsertOne) SetResourceID(v uint) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdateResourceID() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateResourceID()
	})
}

// SetResourceItemID sets the "resource_item_id" field.
func (u *ResourceOrderUpsertOne) SetResourceItemID(v uint) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetResourceItemID(v)
	})
}

// UpdateResourceItemID sets the "resource_item_id" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdateResourceItemID() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateResourceItemID()
	})
}

// ClearResourceItemID clears the value of the "resource_item_id" field.
func (u *ResourceOrderUpsertOne) ClearResourceItemID() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.ClearResourceItemID()
	})
}

// SetBusinessOrderNo sets the "business_order_no" field.
func (u *ResourceOrderUpsertOne) SetBusinessOrderNo(v string) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetBusinessOrderNo(v)
	})
}

// UpdateBusinessOrderNo sets the "business_order_no" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdateBusinessOrderNo() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateBusinessOrderNo()
	})
}

// SetExternalOrderNo sets the "external_order_no" field.
func (u *ResourceOrderUpsertOne) SetExternalOrderNo(v string) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetExternalOrderNo(v)
	})
}

// UpdateExternalOrderNo sets the "external_order_no" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdateExternalOrderNo() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateExternalOrderNo()
	})
}

// ClearExternalOrderNo clears the value of the "external_order_no" field.
func (u *ResourceOrderUpsertOne) ClearExternalOrderNo() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.ClearExternalOrderNo()
	})
}

// SetAmount sets the "amount" field.
func (u *ResourceOrderUpsertOne) SetAmount(v float64) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ResourceOrderUpsertOne) AddAmount(v float64) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdateAmount() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ResourceOrderUpsertOne) SetStatus(v string) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdateStatus() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetSnapshot sets the "snapshot" field.
func (u *ResourceOrderUpsertOne) SetSnapshot(v map[string]interface{}) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetSnapshot(v)
	})
}

// UpdateSnapshot sets the "snapshot" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdateSnapshot() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateSnapshot()
	})
}

// ClearSnapshot clears the value of the "snapshot" field.
func (u *ResourceOrderUpsertOne) ClearSnapshot() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.ClearSnapshot()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *ResourceOrderUpsertOne) SetPaidAt(v time.Time) *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *ResourceOrderUpsertOne) UpdatePaidAt() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *ResourceOrderUpsertOne) ClearPaidAt() *ResourceOrderUpsertOne {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.ClearPaidAt()
	})
}

// Exec executes the query.
func (u *ResourceOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResourceOrderUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResourceOrderUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResourceOrderCreateBulk is the builder for creating many ResourceOrder entities in bulk.
type ResourceOrderCreateBulk struct {
	config
	err      error
	builders []*ResourceOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the ResourceOrder entities in the database.
func (_c *ResourceOrderCreateBulk) Save(ctx context.Context) ([]*ResourceOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResourceOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceOrderCreateBulk) SaveX(ctx context.Context) []*ResourceOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResourceOrderUpsertBulk {
	_c.conflict = opts
	return &ResourceOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceOrderCreateBulk) OnConflictColumns(columns ...string) *ResourceOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceOrderUpsertBulk{
		create: _c,
	}
}

// ResourceOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of ResourceOrder nodes.
type ResourceOrderUpsertBulk struct {
	create *ResourceOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResourceOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resourceorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResourceOrderUpsertBulk) UpdateNewValues() *ResourceOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(resourceorder.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resourceorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResourceOrderUpsertBulk) Ignore() *ResourceOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceOrderUpsertBulk) DoNothing() *ResourceOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceOrderCreateBulk.OnConflict
// documentation for more info.
func (u *ResourceOrderUpsertBulk) Update(set func(*ResourceOrderUpsert)) *ResourceOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceOrderUpsertBulk) SetUpdatedAt(v time.Time) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdateUpdatedAt() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResourceOrderUpsertBulk) SetUserID(v int64) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResourceOrderUpsertBulk) AddUserID(v int64) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdateUserID() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *ResourceOrderUpsertBulk) SetResourceID(v uint) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdateResourceID() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateResourceID()
	})
}

// SetResourceItemID sets the "resource_item_id" field.
func (u *ResourceOrderUpsertBulk) SetResourceItemID(v uint) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetResourceItemID(v)
	})
}

// UpdateResourceItemID sets the "resource_item_id" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdateResourceItemID() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateResourceItemID()
	})
}

// ClearResourceItemID clears the value of the "resource_item_id" field.
func (u *ResourceOrderUpsertBulk) ClearResourceItemID() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.ClearResourceItemID()
	})
}

// SetBusinessOrderNo sets the "business_order_no" field.
func (u *ResourceOrderUpsertBulk) SetBusinessOrderNo(v string) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetBusinessOrderNo(v)
	})
}

// UpdateBusinessOrderNo sets the "business_order_no" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdateBusinessOrderNo() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateBusinessOrderNo()
	})
}

// SetExternalOrderNo sets the "external_order_no" field.
func (u *ResourceOrderUpsertBulk) SetExternalOrderNo(v string) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetExternalOrderNo(v)
	})
}

// UpdateExternalOrderNo sets the "external_order_no" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdateExternalOrderNo() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateExternalOrderNo()
	})
}

// ClearExternalOrderNo clears the value of the "external_order_no" field.
func (u *ResourceOrderUpsertBulk) ClearExternalOrderNo() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.ClearExternalOrderNo()
	})
}

// SetAmount sets the "amount" field.
func (u *ResourceOrderUpsertBulk) SetAmount(v float64) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ResourceOrderUpsertBulk) AddAmount(v float64) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdateAmount() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ResourceOrderUpsertBulk) SetStatus(v string) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdateStatus() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetSnapshot sets the "snapshot" field.
func (u *ResourceOrderUpsertBulk) SetSnapshot(v map[string]interface{}) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetSnapshot(v)
	})
}

// UpdateSnapshot sets the "snapshot" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdateSnapshot() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdateSnapshot()
	})
}

// ClearSnapshot clears the value of the "snapshot" field.
func (u *ResourceOrderUpsertBulk) ClearSnapshot() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.ClearSnapshot()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *ResourceOrderUpsertBulk) SetPaidAt(v time.Time) *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *ResourceOrderUpsertBulk) UpdatePaidAt() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *ResourceOrderUpsertBulk) ClearPaidAt() *ResourceOrderUpsertBulk {
	return u.Update(func(s *ResourceOrderUpsert) {
		s.ClearPaidAt()
	})
}

// Exec executes the query.
func (u *ResourceOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResourceOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
