// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
	"github.com/anzhiyu-c/anheyu-app/ent/resource"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceitem"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceorder"
)

// ResourceOrderQuery is the builder for querying ResourceOrder entities.
type ResourceOrderQuery struct {
	config
	ctx              *QueryContext
	order            []resourceorder.OrderOption
	inters           []Interceptor
	predicates       []predicate.ResourceOrder
	withResource     *ResourceQuery
	withResourceItem *ResourceItemQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResourceOrderQuery builder.
func (_q *ResourceOrderQuery) Where(ps ...predicate.ResourceOrder) *ResourceOrderQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ResourceOrderQuery) Limit(limit int) *ResourceOrderQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ResourceOrderQuery) Offset(offset int) *ResourceOrderQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ResourceOrderQuery) Unique(unique bool) *ResourceOrderQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ResourceOrderQuery) Order(o ...resourceorder.OrderOption) *ResourceOrderQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryResource chains the current query on the "resource" edge.
func (_q *ResourceOrderQuery) QueryResource() *ResourceQuery {
	query := (&ResourceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourceorder.Table, resourceorder.FieldID, selector),
			sqlgraph.To(resource.Table, resource.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, resourceorder.ResourceTable, resourceorder.ResourceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryResourceItem chains the current query on the "resource_item" edge.
func (_q *ResourceOrderQuery) QueryResourceItem() *ResourceItemQuery {
	query := (&ResourceItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourceorder.Table, resourceorder.FieldID, selector),
			sqlgraph.To(resourceitem.Table, resourceitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, resourceorder.ResourceItemTable, resourceorder.ResourceItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ResourceOrder entity from the query.
// Returns a *NotFoundError when no ResourceOrder was found.
func (_q *ResourceOrderQuery) First(ctx context.Context) (*ResourceOrder, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{resourceorder.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ResourceOrderQuery) FirstX(ctx context.Context) *ResourceOrder {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ResourceOrder ID from the query.
// Returns a *NotFoundError when no ResourceOrder ID was found.
func (_q *ResourceOrderQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{resourceorder.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ResourceOrderQuery) FirstIDX(ctx context.Context) uint {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ResourceOrder entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ResourceOrder entity is found.
// Returns a *NotFoundError when no ResourceOrder entities are found.
func (_q *ResourceOrderQuery) Only(ctx context.Context) (*ResourceOrder, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{resourceorder.Label}
	default:
		return nil, &NotSingularError{resourceorder.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ResourceOrderQuery) OnlyX(ctx context.Context) *ResourceOrder {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ResourceOrder ID in the query.
// Returns a *NotSingularError when more than one ResourceOrder ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ResourceOrderQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{resourceorder.Label}
	default:
		err = &NotSingularError{resourceorder.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ResourceOrderQuery) OnlyIDX(ctx context.Context) uint {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ResourceOrders.
func (_q *ResourceOrderQuery) All(ctx context.Context) ([]*ResourceOrder, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ResourceOrder, *ResourceOrderQuery]()
	return withInterceptors[[]*ResourceOrder](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ResourceOrderQuery) AllX(ctx context.Context) []*ResourceOrder {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ResourceOrder IDs.
func (_q *ResourceOrderQuery) IDs(ctx context.Context) (ids []uint, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(resourceorder.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ResourceOrderQuery) IDsX(ctx context.Context) []uint {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ResourceOrderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ResourceOrderQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ResourceOrderQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ResourceOrderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ResourceOrderQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResourceOrderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ResourceOrderQuery) Clone() *ResourceOrderQuery {
	if _q == nil {
		return nil
	}
	return &ResourceOrderQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]resourceorder.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.ResourceOrder{}, _q.predicates...),
		withResource:     _q.withResource.Clone(),
		withResourceItem: _q.withResourceItem.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithResource tells the query-builder to eager-load the nodes that are connected to
// the "resource" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResourceOrderQuery) WithResource(opts ...func(*ResourceQuery)) *ResourceOrderQuery {
	query := (&ResourceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withResource = query
	return _q
}

// WithResourceItem tells the query-builder to eager-load the nodes that are connected to
// the "resource_item" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResourceOrderQuery) WithResourceItem(opts ...func(*ResourceItemQuery)) *ResourceOrderQuery {
	query := (&ResourceItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withResourceItem = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ResourceOrder.Query().
//		GroupBy(resourceorder.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ResourceOrderQuery) GroupBy(field string, fields ...string) *ResourceOrderGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ResourceOrderGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = resourceorder.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ResourceOrder.Query().
//		Select(resourceorder.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ResourceOrderQuery) Select(fields ...string) *ResourceOrderSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ResourceOrderSelect{ResourceOrderQuery: _q}
	sbuild.label = resourceorder.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ResourceOrderSelect configured with the given aggregations.
func (_q *ResourceOrderQuery) Aggregate(fns ...AggregateFunc) *ResourceOrderSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ResourceOrderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !resourceorder.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ResourceOrderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ResourceOrder, error) {
	var (
		nodes       = []*ResourceOrder{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withResource != nil,
			_q.withResourceItem != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ResourceOrder).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ResourceOrder{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withResource; query != nil {
		if err := _q.loadResource(ctx, query, nodes, nil,
			func(n *ResourceOrder, e *Resource) { n.Edges.Resource = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withResourceItem; query != nil {
		if err := _q.loadResourceItem(ctx, query, nodes, nil,
			func(n *ResourceOrder, e *ResourceItem) { n.Edges.ResourceItem = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ResourceOrderQuery) loadResource(ctx context.Context, query *ResourceQuery, nodes []*ResourceOrder, init func(*ResourceOrder), assign func(*ResourceOrder, *Resource)) error {
	ids := make([]uint, 0, len(nodes))
	nodeids := make(map[uint][]*ResourceOrder)
	for i := range nodes {
		fk := nodes[i].ResourceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(resource.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "resource_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ResourceOrderQuery) loadResourceItem(ctx context.Context, query *ResourceItemQuery, nodes []*ResourceOrder, init func(*ResourceOrder), assign func(*ResourceOrder, *ResourceItem)) error {
	ids := make([]uint, 0, len(nodes))
	nodeids := make(map[uint][]*ResourceOrder)
	for i := range nodes {
		if nodes[i].ResourceItemID == nil {
			continue
		}
		fk := *nodes[i].ResourceItemID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(resourceitem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "resource_item_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ResourceOrderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ResourceOrderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(resourceorder.Table, resourceorder.Columns, sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourceorder.FieldID)
		for i := range fields {
			if fields[i] != resourceorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withResource != nil {
			_spec.Node.AddColumnOnce(resourceorder.FieldResourceID)
		}
		if _q.withResourceItem != nil {
			_spec.Node.AddColumnOnce(resourceorder.FieldResourceItemID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ResourceOrderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(resourceorder.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = resourceorder.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ResourceOrderQuery) Modify(modifiers ...func(s *sql.Selector)) *ResourceOrderSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// ResourceOrderGroupBy is the group-by builder for ResourceOrder entities.
type ResourceOrderGroupBy struct {
	selector
	build *ResourceOrderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ResourceOrderGroupBy) Aggregate(fns ...AggregateFunc) *ResourceOrderGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ResourceOrderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResourceOrderQuery, *ResourceOrderGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ResourceOrderGroupBy) sqlScan(ctx context.Context, root *ResourceOrderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ResourceOrderSelect is the builder for selecting fields of ResourceOrder entities.
type ResourceOrderSelect struct {
	*ResourceOrderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ResourceOrderSelect) Aggregate(fns ...AggregateFunc) *ResourceOrderSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ResourceOrderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResourceOrderQuery, *ResourceOrderSelect](ctx, _s.ResourceOrderQuery, _s, _s.inters, v)
}

func (_s *ResourceOrderSelect) sqlScan(ctx context.Context, root *ResourceOrderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ResourceOrderSelect) Modify(modifiers ...func(s *sql.Selector)) *ResourceOrderSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
