// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/resource"
)

// 独立资源销售单元表
type Resource struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 资源宿主类型，如 article 或 product
	HostType string `json:"host_type,omitempty"`
	// 资源宿主公共 ID
	HostID string `json:"host_id,omitempty"`
	// 资源标题
	Title string `json:"title,omitempty"`
	// 资源摘要
	Summary string `json:"summary,omitempty"`
	// 资源封面图 URL
	CoverURL string `json:"cover_url,omitempty"`
	// 资源类型
	ResourceType string `json:"resource_type,omitempty"`
	// 资源状态：draft/published/archived
	Status string `json:"status,omitempty"`
	// 是否启用销售
	SaleEnabled bool `json:"sale_enabled,omitempty"`
	// 销售价格
	Price float64 `json:"price,omitempty"`
	// 划线价格
	OriginalPrice float64 `json:"original_price,omitempty"`
	// 会员是否免费
	MemberFree bool `json:"member_free,omitempty"`
	// 同宿主内排序，越小越靠前
	Sort int `json:"sort,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResourceQuery when eager-loading is set.
	Edges        ResourceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResourceEdges holds the relations/edges for other nodes in the graph.
type ResourceEdges struct {
	// Items holds the value of the items edge.
	Items []*ResourceItem `json:"items,omitempty"`
	// Orders holds the value of the orders edge.
	Orders []*ResourceOrder `json:"orders,omitempty"`
	// AccessGrants holds the value of the access_grants edge.
	AccessGrants []*ResourceAccessGrant `json:"access_grants,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e ResourceEdges) ItemsOrErr() ([]*ResourceItem, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e ResourceEdges) OrdersOrErr() ([]*ResourceOrder, error) {
	if e.loadedTypes[1] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// AccessGrantsOrErr returns the AccessGrants value or an error if the edge
// was not loaded in eager-loading.
func (e ResourceEdges) AccessGrantsOrErr() ([]*ResourceAccessGrant, error) {
	if e.loadedTypes[2] {
		return e.AccessGrants, nil
	}
	return nil, &NotLoadedError{edge: "access_grants"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Resource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resource.FieldSaleEnabled, resource.FieldMemberFree:
			values[i] = new(sql.NullBool)
		case resource.FieldPrice, resource.FieldOriginalPrice:
			values[i] = new(sql.NullFloat64)
		case resource.FieldID, resource.FieldSort:
			values[i] = new(sql.NullInt64)
		case resource.FieldHostType, resource.FieldHostID, resource.FieldTitle, resource.FieldSummary, resource.FieldCoverURL, resource.FieldResourceType, resource.FieldStatus:
			values[i] = new(sql.NullString)
		case resource.FieldDeletedAt, resource.FieldCreatedAt, resource.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Resource fields.
func (_m *Resource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case resource.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case resource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case resource.FieldHostType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host_type", values[i])
			} else if value.Valid {
				_m.HostType = value.String
			}
		case resource.FieldHostID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host_id", values[i])
			} else if value.Valid {
				_m.HostID = value.String
			}
		case resource.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case resource.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case resource.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				_m.CoverURL = value.String
			}
		case resource.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = value.String
			}
		case resource.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case resource.FieldSaleEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sale_enabled", values[i])
			} else if value.Valid {
				_m.SaleEnabled = value.Bool
			}
		case resource.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case resource.FieldOriginalPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field original_price", values[i])
			} else if value.Valid {
				_m.OriginalPrice = value.Float64
			}
		case resource.FieldMemberFree:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field member_free", values[i])
			} else if value.Valid {
				_m.MemberFree = value.Bool
			}
		case resource.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Resource.
// This includes values selected through modifiers, order, etc.
func (_m *Resource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the Resource entity.
func (_m *Resource) QueryItems() *ResourceItemQuery {
	return NewResourceClient(_m.config).QueryItems(_m)
}

// QueryOrders queries the "orders" edge of the Resource entity.
func (_m *Resource) QueryOrders() *ResourceOrderQuery {
	return NewResourceClient(_m.config).QueryOrders(_m)
}

// QueryAccessGrants queries the "access_grants" edge of the Resource entity.
func (_m *Resource) QueryAccessGrants() *ResourceAccessGrantQuery {
	return NewResourceClient(_m.config).QueryAccessGrants(_m)
}

// Update returns a builder for updating this Resource.
// Note that you need to call Resource.Unwrap() before calling this method if this Resource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Resource) Update() *ResourceUpdateOne {
	return NewResourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Resource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Resource) Unwrap() *Resource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Resource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Resource) String() string {
	var builder strings.Builder
	builder.WriteString("Resource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("host_type=")
	builder.WriteString(_m.HostType)
	builder.WriteString(", ")
	builder.WriteString("host_id=")
	builder.WriteString(_m.HostID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("cover_url=")
	builder.WriteString(_m.CoverURL)
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(_m.ResourceType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("sale_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.SaleEnabled))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("original_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.OriginalPrice))
	builder.WriteString(", ")
	builder.WriteString("member_free=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemberFree))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteByte(')')
	return builder.String()
}

// Resources is a parsable slice of Resource.
type Resources []*Resource
