// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/resource"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceitem"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceorder"
)

// 资源本地业务订单映射表
type ResourceOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 阳光栈本地用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 关联资源 ID
	ResourceID uint `json:"resource_id,omitempty"`
	// 关联资源交付物 ID，可空
	ResourceItemID *uint `json:"resource_item_id,omitempty"`
	// 阳光栈业务订单号
	BusinessOrderNo string `json:"business_order_no,omitempty"`
	// 外部支付单号，如极光库订单号
	ExternalOrderNo string `json:"external_order_no,omitempty"`
	// 订单金额
	Amount float64 `json:"amount,omitempty"`
	// 订单状态
	Status string `json:"status,omitempty"`
	// 下单时的业务快照
	Snapshot map[string]interface{} `json:"snapshot,omitempty"`
	// 支付完成时间
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResourceOrderQuery when eager-loading is set.
	Edges        ResourceOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResourceOrderEdges holds the relations/edges for other nodes in the graph.
type ResourceOrderEdges struct {
	// Resource holds the value of the resource edge.
	Resource *Resource `json:"resource,omitempty"`
	// ResourceItem holds the value of the resource_item edge.
	ResourceItem *ResourceItem `json:"resource_item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ResourceOrErr returns the Resource value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResourceOrderEdges) ResourceOrErr() (*Resource, error) {
	if e.Resource != nil {
		return e.Resource, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: resource.Label}
	}
	return nil, &NotLoadedError{edge: "resource"}
}

// ResourceItemOrErr returns the ResourceItem value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResourceOrderEdges) ResourceItemOrErr() (*ResourceItem, error) {
	if e.ResourceItem != nil {
		return e.ResourceItem, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: resourceitem.Label}
	}
	return nil, &NotLoadedError{edge: "resource_item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResourceOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resourceorder.FieldSnapshot:
			values[i] = new([]byte)
		case resourceorder.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case resourceorder.FieldID, resourceorder.FieldUserID, resourceorder.FieldResourceID, resourceorder.FieldResourceItemID:
			values[i] = new(sql.NullInt64)
		case resourceorder.FieldBusinessOrderNo, resourceorder.FieldExternalOrderNo, resourceorder.FieldStatus:
			values[i] = new(sql.NullString)
		case resourceorder.FieldCreatedAt, resourceorder.FieldUpdatedAt, resourceorder.FieldPaidAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResourceOrder fields.
func (_m *ResourceOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resourceorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case resourceorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resourceorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case resourceorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case resourceorder.FieldResourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = uint(value.Int64)
			}
		case resourceorder.FieldResourceItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resource_item_id", values[i])
			} else if value.Valid {
				_m.ResourceItemID = new(uint)
				*_m.ResourceItemID = uint(value.Int64)
			}
		case resourceorder.FieldBusinessOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field business_order_no", values[i])
			} else if value.Valid {
				_m.BusinessOrderNo = value.String
			}
		case resourceorder.FieldExternalOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_order_no", values[i])
			} else if value.Valid {
				_m.ExternalOrderNo = value.String
			}
		case resourceorder.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case resourceorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case resourceorder.FieldSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Snapshot); err != nil {
					return fmt.Errorf("unmarshal field snapshot: %w", err)
				}
			}
		case resourceorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResourceOrder.
// This includes values selected through modifiers, order, etc.
func (_m *ResourceOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryResource queries the "resource" edge of the ResourceOrder entity.
func (_m *ResourceOrder) QueryResource() *ResourceQuery {
	return NewResourceOrderClient(_m.config).QueryResource(_m)
}

// QueryResourceItem queries the "resource_item" edge of the ResourceOrder entity.
func (_m *ResourceOrder) QueryResourceItem() *ResourceItemQuery {
	return NewResourceOrderClient(_m.config).QueryResourceItem(_m)
}

// Update returns a builder for updating this ResourceOrder.
// Note that you need to call ResourceOrder.Unwrap() before calling this method if this ResourceOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResourceOrder) Update() *ResourceOrderUpdateOne {
	return NewResourceOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResourceOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResourceOrder) Unwrap() *ResourceOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResourceOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResourceOrder) String() string {
	var builder strings.Builder
	builder.WriteString("ResourceOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceID))
	builder.WriteString(", ")
	if v := _m.ResourceItemID; v != nil {
		builder.WriteString("resource_item_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("business_order_no=")
	builder.WriteString(_m.BusinessOrderNo)
	builder.WriteString(", ")
	builder.WriteString("external_order_no=")
	builder.WriteString(_m.ExternalOrderNo)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.Snapshot))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ResourceOrders is a parsable slice of ResourceOrder.
type ResourceOrders []*ResourceOrder
