// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
	"github.com/anzhiyu-c/anheyu-app/ent/resource"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceaccessgrant"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceitem"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceorder"
)

// ResourceUpdate is the builder for updating Resource entities.
type ResourceUpdate struct {
	config
	hooks     []Hook
	mutation  *ResourceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdate) Where(ps ...predicate.Resource) *ResourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResourceUpdate) SetDeletedAt(v time.Time) *ResourceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableDeletedAt(v *time.Time) *ResourceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResourceUpdate) ClearDeletedAt() *ResourceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceUpdate) SetUpdatedAt(v time.Time) *ResourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHostType sets the "host_type" field.
func (_u *ResourceUpdate) SetHostType(v string) *ResourceUpdate {
	_u.mutation.SetHostType(v)
	return _u
}

// SetNillableHostType sets the "host_type" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableHostType(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetHostType(*v)
	}
	return _u
}

// SetHostID sets the "host_id" field.
func (_u *ResourceUpdate) SetHostID(v string) *ResourceUpdate {
	_u.mutation.SetHostID(v)
	return _u
}

// SetNillableHostID sets the "host_id" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableHostID(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetHostID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ResourceUpdate) SetTitle(v string) *ResourceUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableTitle(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ResourceUpdate) SetSummary(v string) *ResourceUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableSummary(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *ResourceUpdate) ClearSummary() *ResourceUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *ResourceUpdate) SetCoverURL(v string) *ResourceUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableCoverURL(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *ResourceUpdate) ClearCoverURL() *ResourceUpdate {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ResourceUpdate) SetResourceType(v string) *ResourceUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableResourceType(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdate) SetStatus(v string) *ResourceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableStatus(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSaleEnabled sets the "sale_enabled" field.
func (_u *ResourceUpdate) SetSaleEnabled(v bool) *ResourceUpdate {
	_u.mutation.SetSaleEnabled(v)
	return _u
}

// SetNillableSaleEnabled sets the "sale_enabled" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableSaleEnabled(v *bool) *ResourceUpdate {
	if v != nil {
		_u.SetSaleEnabled(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *ResourceUpdate) SetPrice(v float64) *ResourceUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillablePrice(v *float64) *ResourceUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *ResourceUpdate) AddPrice(v float64) *ResourceUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *ResourceUpdate) SetOriginalPrice(v float64) *ResourceUpdate {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableOriginalPrice(v *float64) *ResourceUpdate {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *ResourceUpdate) AddOriginalPrice(v float64) *ResourceUpdate {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// SetMemberFree sets the "member_free" field.
func (_u *ResourceUpdate) SetMemberFree(v bool) *ResourceUpdate {
	_u.mutation.SetMemberFree(v)
	return _u
}

// SetNillableMemberFree sets the "member_free" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableMemberFree(v *bool) *ResourceUpdate {
	if v != nil {
		_u.SetMemberFree(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *ResourceUpdate) SetSort(v int) *ResourceUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableSort(v *int) *ResourceUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *ResourceUpdate) AddSort(v int) *ResourceUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// AddItemIDs adds the "items" edge to the ResourceItem entity by IDs.
func (_u *ResourceUpdate) AddItemIDs(ids ...uint) *ResourceUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the ResourceItem entity.
func (_u *ResourceUpdate) AddItems(v ...*ResourceItem) *ResourceUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddOrderIDs adds the "orders" edge to the ResourceOrder entity by IDs.
func (_u *ResourceUpdate) AddOrderIDs(ids ...uint) *ResourceUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the ResourceOrder entity.
func (_u *ResourceUpdate) AddOrders(v ...*ResourceOrder) *ResourceUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// AddAccessGrantIDs adds the "access_grants" edge to the ResourceAccessGrant entity by IDs.
func (_u *ResourceUpdate) AddAccessGrantIDs(ids ...uint) *ResourceUpdate {
	_u.mutation.AddAccessGrantIDs(ids...)
	return _u
}

// AddAccessGrants adds the "access_grants" edges to the ResourceAccessGrant entity.
func (_u *ResourceUpdate) AddAccessGrants(v ...*ResourceAccessGrant) *ResourceUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccessGrantIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdate) Mutation() *ResourceMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the ResourceItem entity.
func (_u *ResourceUpdate) ClearItems() *ResourceUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to ResourceItem entities by IDs.
func (_u *ResourceUpdate) RemoveItemIDs(ids ...uint) *ResourceUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to ResourceItem entities.
func (_u *ResourceUpdate) RemoveItems(v ...*ResourceItem) *ResourceUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearOrders clears all "orders" edges to the ResourceOrder entity.
func (_u *ResourceUpdate) ClearOrders() *ResourceUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to ResourceOrder entities by IDs.
func (_u *ResourceUpdate) RemoveOrderIDs(ids ...uint) *ResourceUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to ResourceOrder entities.
func (_u *ResourceUpdate) RemoveOrders(v ...*ResourceOrder) *ResourceUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// ClearAccessGrants clears all "access_grants" edges to the ResourceAccessGrant entity.
func (_u *ResourceUpdate) ClearAccessGrants() *ResourceUpdate {
	_u.mutation.ClearAccessGrants()
	return _u
}

// RemoveAccessGrantIDs removes the "access_grants" edge to ResourceAccessGrant entities by IDs.
func (_u *ResourceUpdate) RemoveAccessGrantIDs(ids ...uint) *ResourceUpdate {
	_u.mutation.RemoveAccessGrantIDs(ids...)
	return _u
}

// RemoveAccessGrants removes "access_grants" edges to ResourceAccessGrant entities.
func (_u *ResourceUpdate) RemoveAccessGrants(v ...*ResourceAccessGrant) *ResourceUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccessGrantIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if resource.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized resource.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := resource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdate) check() error {
	if v, ok := _u.mutation.HostType(); ok {
		if err := resource.HostTypeValidator(v); err != nil {
			return &ValidationError{Name: "host_type", err: fmt.Errorf(`ent: validator failed for field "Resource.host_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HostID(); ok {
		if err := resource.HostIDValidator(v); err != nil {
			return &ValidationError{Name: "host_id", err: fmt.Errorf(`ent: validator failed for field "Resource.host_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := resource.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Resource.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := resource.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Resource.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := resource.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "Resource.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := resource.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Resource.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resource.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Resource.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ResourceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResourceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ResourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HostType(); ok {
		_spec.SetField(resource.FieldHostType, field.TypeString, value)
	}
	if value, ok := _u.mutation.HostID(); ok {
		_spec.SetField(resource.FieldHostID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(resource.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(resource.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(resource.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(resource.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(resource.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(resource.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SaleEnabled(); ok {
		_spec.SetField(resource.FieldSaleEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(resource.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(resource.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(resource.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(resource.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MemberFree(); ok {
		_spec.SetField(resource.FieldMemberFree, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(resource.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(resource.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ItemsTable,
			Columns: []string{resource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ItemsTable,
			Columns: []string{resource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ItemsTable,
			Columns: []string{resource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.OrdersTable,
			Columns: []string{resource.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.OrdersTable,
			Columns: []string{resource.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.OrdersTable,
			Columns: []string{resource.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccessGrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AccessGrantsTable,
			Columns: []string{resource.AccessGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceaccessgrant.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccessGrantsIDs(); len(nodes) > 0 && !_u.mutation.AccessGrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AccessGrantsTable,
			Columns: []string{resource.AccessGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceaccessgrant.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessGrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AccessGrantsTable,
			Columns: []string{resource.AccessGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceaccessgrant.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceUpdateOne is the builder for updating a single Resource entity.
type ResourceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ResourceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResourceUpdateOne) SetDeletedAt(v time.Time) *ResourceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableDeletedAt(v *time.Time) *ResourceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResourceUpdateOne) ClearDeletedAt() *ResourceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceUpdateOne) SetUpdatedAt(v time.Time) *ResourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHostType sets the "host_type" field.
func (_u *ResourceUpdateOne) SetHostType(v string) *ResourceUpdateOne {
	_u.mutation.SetHostType(v)
	return _u
}

// SetNillableHostType sets the "host_type" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableHostType(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetHostType(*v)
	}
	return _u
}

// SetHostID sets the "host_id" field.
func (_u *ResourceUpdateOne) SetHostID(v string) *ResourceUpdateOne {
	_u.mutation.SetHostID(v)
	return _u
}

// SetNillableHostID sets the "host_id" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableHostID(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetHostID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ResourceUpdateOne) SetTitle(v string) *ResourceUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableTitle(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ResourceUpdateOne) SetSummary(v string) *ResourceUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableSummary(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *ResourceUpdateOne) ClearSummary() *ResourceUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *ResourceUpdateOne) SetCoverURL(v string) *ResourceUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableCoverURL(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *ResourceUpdateOne) ClearCoverURL() *ResourceUpdateOne {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ResourceUpdateOne) SetResourceType(v string) *ResourceUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableResourceType(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdateOne) SetStatus(v string) *ResourceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableStatus(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSaleEnabled sets the "sale_enabled" field.
func (_u *ResourceUpdateOne) SetSaleEnabled(v bool) *ResourceUpdateOne {
	_u.mutation.SetSaleEnabled(v)
	return _u
}

// SetNillableSaleEnabled sets the "sale_enabled" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableSaleEnabled(v *bool) *ResourceUpdateOne {
	if v != nil {
		_u.SetSaleEnabled(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *ResourceUpdateOne) SetPrice(v float64) *ResourceUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillablePrice(v *float64) *ResourceUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *ResourceUpdateOne) AddPrice(v float64) *ResourceUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *ResourceUpdateOne) SetOriginalPrice(v float64) *ResourceUpdateOne {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableOriginalPrice(v *float64) *ResourceUpdateOne {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *ResourceUpdateOne) AddOriginalPrice(v float64) *ResourceUpdateOne {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// SetMemberFree sets the "member_free" field.
func (_u *ResourceUpdateOne) SetMemberFree(v bool) *ResourceUpdateOne {
	_u.mutation.SetMemberFree(v)
	return _u
}

// SetNillableMemberFree sets the "member_free" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableMemberFree(v *bool) *ResourceUpdateOne {
	if v != nil {
		_u.SetMemberFree(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *ResourceUpdateOne) SetSort(v int) *ResourceUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableSort(v *int) *ResourceUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *ResourceUpdateOne) AddSort(v int) *ResourceUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// AddItemIDs adds the "items" edge to the ResourceItem entity by IDs.
func (_u *ResourceUpdateOne) AddItemIDs(ids ...uint) *ResourceUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the ResourceItem entity.
func (_u *ResourceUpdateOne) AddItems(v ...*ResourceItem) *ResourceUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddOrderIDs adds the "orders" edge to the ResourceOrder entity by IDs.
func (_u *ResourceUpdateOne) AddOrderIDs(ids ...uint) *ResourceUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the ResourceOrder entity.
func (_u *ResourceUpdateOne) AddOrders(v ...*ResourceOrder) *ResourceUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// AddAccessGrantIDs adds the "access_grants" edge to the ResourceAccessGrant entity by IDs.
func (_u *ResourceUpdateOne) AddAccessGrantIDs(ids ...uint) *ResourceUpdateOne {
	_u.mutation.AddAccessGrantIDs(ids...)
	return _u
}

// AddAccessGrants adds the "access_grants" edges to the ResourceAccessGrant entity.
func (_u *ResourceUpdateOne) AddAccessGrants(v ...*ResourceAccessGrant) *ResourceUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccessGrantIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdateOne) Mutation() *ResourceMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the ResourceItem entity.
func (_u *ResourceUpdateOne) ClearItems() *ResourceUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to ResourceItem entities by IDs.
func (_u *ResourceUpdateOne) RemoveItemIDs(ids ...uint) *ResourceUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to ResourceItem entities.
func (_u *ResourceUpdateOne) RemoveItems(v ...*ResourceItem) *ResourceUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearOrders clears all "orders" edges to the ResourceOrder entity.
func (_u *ResourceUpdateOne) ClearOrders() *ResourceUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to ResourceOrder entities by IDs.
func (_u *ResourceUpdateOne) RemoveOrderIDs(ids ...uint) *ResourceUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to ResourceOrder entities.
func (_u *ResourceUpdateOne) RemoveOrders(v ...*ResourceOrder) *ResourceUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// ClearAccessGrants clears all "access_grants" edges to the ResourceAccessGrant entity.
func (_u *ResourceUpdateOne) ClearAccessGrants() *ResourceUpdateOne {
	_u.mutation.ClearAccessGrants()
	return _u
}

// RemoveAccessGrantIDs removes the "access_grants" edge to ResourceAccessGrant entities by IDs.
func (_u *ResourceUpdateOne) RemoveAccessGrantIDs(ids ...uint) *ResourceUpdateOne {
	_u.mutation.RemoveAccessGrantIDs(ids...)
	return _u
}

// RemoveAccessGrants removes "access_grants" edges to ResourceAccessGrant entities.
func (_u *ResourceUpdateOne) RemoveAccessGrants(v ...*ResourceAccessGrant) *ResourceUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccessGrantIDs(ids...)
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdateOne) Where(ps ...predicate.Resource) *ResourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceUpdateOne) Select(field string, fields ...string) *ResourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Resource entity.
func (_u *ResourceUpdateOne) Save(ctx context.Context) (*Resource, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdateOne) SaveX(ctx context.Context) *Resource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if resource.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized resource.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := resource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdateOne) check() error {
	if v, ok := _u.mutation.HostType(); ok {
		if err := resource.HostTypeValidator(v); err != nil {
			return &ValidationError{Name: "host_type", err: fmt.Errorf(`ent: validator failed for field "Resource.host_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HostID(); ok {
		if err := resource.HostIDValidator(v); err != nil {
			return &ValidationError{Name: "host_id", err: fmt.Errorf(`ent: validator failed for field "Resource.host_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := resource.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Resource.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := resource.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Resource.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := resource.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "Resource.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := resource.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Resource.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resource.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Resource.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ResourceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResourceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ResourceUpdateOne) sqlSave(ctx context.Context) (_node *Resource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Resource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resource.FieldID)
		for _, f := range fields {
			if !resource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HostType(); ok {
		_spec.SetField(resource.FieldHostType, field.TypeString, value)
	}
	if value, ok := _u.mutation.HostID(); ok {
		_spec.SetField(resource.FieldHostID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(resource.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(resource.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(resource.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(resource.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(resource.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(resource.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SaleEnabled(); ok {
		_spec.SetField(resource.FieldSaleEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(resource.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(resource.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(resource.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(resource.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MemberFree(); ok {
		_spec.SetField(resource.FieldMemberFree, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(resource.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(resource.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ItemsTable,
			Columns: []string{resource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ItemsTable,
			Columns: []string{resource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ItemsTable,
			Columns: []string{resource.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.OrdersTable,
			Columns: []string{resource.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.OrdersTable,
			Columns: []string{resource.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.OrdersTable,
			Columns: []string{resource.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccessGrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AccessGrantsTable,
			Columns: []string{resource.AccessGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceaccessgrant.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccessGrantsIDs(); len(nodes) > 0 && !_u.mutation.AccessGrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AccessGrantsTable,
			Columns: []string{resource.AccessGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceaccessgrant.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessGrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AccessGrantsTable,
			Columns: []string{resource.AccessGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceaccessgrant.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Resource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
