// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceorder"
)

// ResourceOrderDelete is the builder for deleting a ResourceOrder entity.
type ResourceOrderDelete struct {
	config
	hooks    []Hook
	mutation *ResourceOrderMutation
}

// Where appends a list predicates to the ResourceOrderDelete builder.
func (_d *ResourceOrderDelete) Where(ps ...predicate.ResourceOrder) *ResourceOrderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ResourceOrderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResourceOrderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ResourceOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(resourceorder.Table, sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ResourceOrderDeleteOne is the builder for deleting a single ResourceOrder entity.
type ResourceOrderDeleteOne struct {
	_d *ResourceOrderDelete
}

// Where appends a list predicates to the ResourceOrderDelete builder.
func (_d *ResourceOrderDeleteOne) Where(ps ...predicate.ResourceOrder) *ResourceOrderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ResourceOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{resourceorder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResourceOrderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
