// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
	"github.com/anzhiyu-c/anheyu-app/ent/resource"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceaccessgrant"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceitem"
)

// ResourceAccessGrantUpdate is the builder for updating ResourceAccessGrant entities.
type ResourceAccessGrantUpdate struct {
	config
	hooks     []Hook
	mutation  *ResourceAccessGrantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ResourceAccessGrantUpdate builder.
func (_u *ResourceAccessGrantUpdate) Where(ps ...predicate.ResourceAccessGrant) *ResourceAccessGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceAccessGrantUpdate) SetUpdatedAt(v time.Time) *ResourceAccessGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResourceAccessGrantUpdate) SetUserID(v int64) *ResourceAccessGrantUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdate) SetNillableUserID(v *int64) *ResourceAccessGrantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResourceAccessGrantUpdate) AddUserID(v int64) *ResourceAccessGrantUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ResourceAccessGrantUpdate) SetResourceID(v uint) *ResourceAccessGrantUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdate) SetNillableResourceID(v *uint) *ResourceAccessGrantUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetResourceItemID sets the "resource_item_id" field.
func (_u *ResourceAccessGrantUpdate) SetResourceItemID(v uint) *ResourceAccessGrantUpdate {
	_u.mutation.SetResourceItemID(v)
	return _u
}

// SetNillableResourceItemID sets the "resource_item_id" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdate) SetNillableResourceItemID(v *uint) *ResourceAccessGrantUpdate {
	if v != nil {
		_u.SetResourceItemID(*v)
	}
	return _u
}

// ClearResourceItemID clears the value of the "resource_item_id" field.
func (_u *ResourceAccessGrantUpdate) ClearResourceItemID() *ResourceAccessGrantUpdate {
	_u.mutation.ClearResourceItemID()
	return _u
}

// SetGrantType sets the "grant_type" field.
func (_u *ResourceAccessGrantUpdate) SetGrantType(v string) *ResourceAccessGrantUpdate {
	_u.mutation.SetGrantType(v)
	return _u
}

// SetNillableGrantType sets the "grant_type" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdate) SetNillableGrantType(v *string) *ResourceAccessGrantUpdate {
	if v != nil {
		_u.SetGrantType(*v)
	}
	return _u
}

// SetSourceOrderNo sets the "source_order_no" field.
func (_u *ResourceAccessGrantUpdate) SetSourceOrderNo(v string) *ResourceAccessGrantUpdate {
	_u.mutation.SetSourceOrderNo(v)
	return _u
}

// SetNillableSourceOrderNo sets the "source_order_no" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdate) SetNillableSourceOrderNo(v *string) *ResourceAccessGrantUpdate {
	if v != nil {
		_u.SetSourceOrderNo(*v)
	}
	return _u
}

// ClearSourceOrderNo clears the value of the "source_order_no" field.
func (_u *ResourceAccessGrantUpdate) ClearSourceOrderNo() *ResourceAccessGrantUpdate {
	_u.mutation.ClearSourceOrderNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceAccessGrantUpdate) SetStatus(v string) *ResourceAccessGrantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdate) SetNillableStatus(v *string) *ResourceAccessGrantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *ResourceAccessGrantUpdate) SetGrantedAt(v time.Time) *ResourceAccessGrantUpdate {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdate) SetNillableGrantedAt(v *time.Time) *ResourceAccessGrantUpdate {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *ResourceAccessGrantUpdate) SetExpiredAt(v time.Time) *ResourceAccessGrantUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdate) SetNillableExpiredAt(v *time.Time) *ResourceAccessGrantUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *ResourceAccessGrantUpdate) ClearExpiredAt() *ResourceAccessGrantUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetResource sets the "resource" edge to the Resource entity.
func (_u *ResourceAccessGrantUpdate) SetResource(v *Resource) *ResourceAccessGrantUpdate {
	return _u.SetResourceID(v.ID)
}

// SetResourceItem sets the "resource_item" edge to the ResourceItem entity.
func (_u *ResourceAccessGrantUpdate) SetResourceItem(v *ResourceItem) *ResourceAccessGrantUpdate {
	return _u.SetResourceItemID(v.ID)
}

// Mutation returns the ResourceAccessGrantMutation object of the builder.
func (_u *ResourceAccessGrantUpdate) Mutation() *ResourceAccessGrantMutation {
	return _u.mutation
}

// ClearResource clears the "resource" edge to the Resource entity.
func (_u *ResourceAccessGrantUpdate) ClearResource() *ResourceAccessGrantUpdate {
	_u.mutation.ClearResource()
	return _u
}

// ClearResourceItem clears the "resource_item" edge to the ResourceItem entity.
func (_u *ResourceAccessGrantUpdate) ClearResourceItem() *ResourceAccessGrantUpdate {
	_u.mutation.ClearResourceItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceAccessGrantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceAccessGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceAccessGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceAccessGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceAccessGrantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resourceaccessgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceAccessGrantUpdate) check() error {
	if v, ok := _u.mutation.GrantType(); ok {
		if err := resourceaccessgrant.GrantTypeValidator(v); err != nil {
			return &ValidationError{Name: "grant_type", err: fmt.Errorf(`ent: validator failed for field "ResourceAccessGrant.grant_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceOrderNo(); ok {
		if err := resourceaccessgrant.SourceOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "source_order_no", err: fmt.Errorf(`ent: validator failed for field "ResourceAccessGrant.source_order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resourceaccessgrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResourceAccessGrant.status": %w`, err)}
		}
	}
	if _u.mutation.ResourceCleared() && len(_u.mutation.ResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResourceAccessGrant.resource"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ResourceAccessGrantUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResourceAccessGrantUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ResourceAccessGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourceaccessgrant.Table, resourceaccessgrant.Columns, sqlgraph.NewFieldSpec(resourceaccessgrant.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resourceaccessgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resourceaccessgrant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resourceaccessgrant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GrantType(); ok {
		_spec.SetField(resourceaccessgrant.FieldGrantType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceOrderNo(); ok {
		_spec.SetField(resourceaccessgrant.FieldSourceOrderNo, field.TypeString, value)
	}
	if _u.mutation.SourceOrderNoCleared() {
		_spec.ClearField(resourceaccessgrant.FieldSourceOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resourceaccessgrant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(resourceaccessgrant.FieldGrantedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(resourceaccessgrant.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(resourceaccessgrant.FieldExpiredAt, field.TypeTime)
	}
	if _u.mutation.ResourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceaccessgrant.ResourceTable,
			Columns: []string{resourceaccessgrant.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceaccessgrant.ResourceTable,
			Columns: []string{resourceaccessgrant.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResourceItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceaccessgrant.ResourceItemTable,
			Columns: []string{resourceaccessgrant.ResourceItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceaccessgrant.ResourceItemTable,
			Columns: []string{resourceaccessgrant.ResourceItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourceaccessgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceAccessGrantUpdateOne is the builder for updating a single ResourceAccessGrant entity.
type ResourceAccessGrantUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ResourceAccessGrantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceAccessGrantUpdateOne) SetUpdatedAt(v time.Time) *ResourceAccessGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResourceAccessGrantUpdateOne) SetUserID(v int64) *ResourceAccessGrantUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdateOne) SetNillableUserID(v *int64) *ResourceAccessGrantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResourceAccessGrantUpdateOne) AddUserID(v int64) *ResourceAccessGrantUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ResourceAccessGrantUpdateOne) SetResourceID(v uint) *ResourceAccessGrantUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdateOne) SetNillableResourceID(v *uint) *ResourceAccessGrantUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetResourceItemID sets the "resource_item_id" field.
func (_u *ResourceAccessGrantUpdateOne) SetResourceItemID(v uint) *ResourceAccessGrantUpdateOne {
	_u.mutation.SetResourceItemID(v)
	return _u
}

// SetNillableResourceItemID sets the "resource_item_id" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdateOne) SetNillableResourceItemID(v *uint) *ResourceAccessGrantUpdateOne {
	if v != nil {
		_u.SetResourceItemID(*v)
	}
	return _u
}

// ClearResourceItemID clears the value of the "resource_item_id" field.
func (_u *ResourceAccessGrantUpdateOne) ClearResourceItemID() *ResourceAccessGrantUpdateOne {
	_u.mutation.ClearResourceItemID()
	return _u
}

// SetGrantType sets the "grant_type" field.
func (_u *ResourceAccessGrantUpdateOne) SetGrantType(v string) *ResourceAccessGrantUpdateOne {
	_u.mutation.SetGrantType(v)
	return _u
}

// SetNillableGrantType sets the "grant_type" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdateOne) SetNillableGrantType(v *string) *ResourceAccessGrantUpdateOne {
	if v != nil {
		_u.SetGrantType(*v)
	}
	return _u
}

// SetSourceOrderNo sets the "source_order_no" field.
func (_u *ResourceAccessGrantUpdateOne) SetSourceOrderNo(v string) *ResourceAccessGrantUpdateOne {
	_u.mutation.SetSourceOrderNo(v)
	return _u
}

// SetNillableSourceOrderNo sets the "source_order_no" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdateOne) SetNillableSourceOrderNo(v *string) *ResourceAccessGrantUpdateOne {
	if v != nil {
		_u.SetSourceOrderNo(*v)
	}
	return _u
}

// ClearSourceOrderNo clears the value of the "source_order_no" field.
func (_u *ResourceAccessGrantUpdateOne) ClearSourceOrderNo() *ResourceAccessGrantUpdateOne {
	_u.mutation.ClearSourceOrderNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceAccessGrantUpdateOne) SetStatus(v string) *ResourceAccessGrantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdateOne) SetNillableStatus(v *string) *ResourceAccessGrantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *ResourceAccessGrantUpdateOne) SetGrantedAt(v time.Time) *ResourceAccessGrantUpdateOne {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdateOne) SetNillableGrantedAt(v *time.Time) *ResourceAccessGrantUpdateOne {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *ResourceAccessGrantUpdateOne) SetExpiredAt(v time.Time) *ResourceAccessGrantUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *ResourceAccessGrantUpdateOne) SetNillableExpiredAt(v *time.Time) *ResourceAccessGrantUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *ResourceAccessGrantUpdateOne) ClearExpiredAt() *ResourceAccessGrantUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetResource sets the "resource" edge to the Resource entity.
func (_u *ResourceAccessGrantUpdateOne) SetResource(v *Resource) *ResourceAccessGrantUpdateOne {
	return _u.SetResourceID(v.ID)
}

// SetResourceItem sets the "resource_item" edge to the ResourceItem entity.
func (_u *ResourceAccessGrantUpdateOne) SetResourceItem(v *ResourceItem) *ResourceAccessGrantUpdateOne {
	return _u.SetResourceItemID(v.ID)
}

// Mutation returns the ResourceAccessGrantMutation object of the builder.
func (_u *ResourceAccessGrantUpdateOne) Mutation() *ResourceAccessGrantMutation {
	return _u.mutation
}

// ClearResource clears the "resource" edge to the Resource entity.
func (_u *ResourceAccessGrantUpdateOne) ClearResource() *ResourceAccessGrantUpdateOne {
	_u.mutation.ClearResource()
	return _u
}

// ClearResourceItem clears the "resource_item" edge to the ResourceItem entity.
func (_u *ResourceAccessGrantUpdateOne) ClearResourceItem() *ResourceAccessGrantUpdateOne {
	_u.mutation.ClearResourceItem()
	return _u
}

// Where appends a list predicates to the ResourceAccessGrantUpdate builder.
func (_u *ResourceAccessGrantUpdateOne) Where(ps ...predicate.ResourceAccessGrant) *ResourceAccessGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceAccessGrantUpdateOne) Select(field string, fields ...string) *ResourceAccessGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResourceAccessGrant entity.
func (_u *ResourceAccessGrantUpdateOne) Save(ctx context.Context) (*ResourceAccessGrant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceAccessGrantUpdateOne) SaveX(ctx context.Context) *ResourceAccessGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceAccessGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceAccessGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceAccessGrantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resourceaccessgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceAccessGrantUpdateOne) check() error {
	if v, ok := _u.mutation.GrantType(); ok {
		if err := resourceaccessgrant.GrantTypeValidator(v); err != nil {
			return &ValidationError{Name: "grant_type", err: fmt.Errorf(`ent: validator failed for field "ResourceAccessGrant.grant_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceOrderNo(); ok {
		if err := resourceaccessgrant.SourceOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "source_order_no", err: fmt.Errorf(`ent: validator failed for field "ResourceAccessGrant.source_order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resourceaccessgrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResourceAccessGrant.status": %w`, err)}
		}
	}
	if _u.mutation.ResourceCleared() && len(_u.mutation.ResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResourceAccessGrant.resource"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ResourceAccessGrantUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResourceAccessGrantUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ResourceAccessGrantUpdateOne) sqlSave(ctx context.Context) (_node *ResourceAccessGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourceaccessgrant.Table, resourceaccessgrant.Columns, sqlgraph.NewFieldSpec(resourceaccessgrant.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResourceAccessGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourceaccessgrant.FieldID)
		for _, f := range fields {
			if !resourceaccessgrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resourceaccessgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resourceaccessgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resourceaccessgrant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resourceaccessgrant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GrantType(); ok {
		_spec.SetField(resourceaccessgrant.FieldGrantType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceOrderNo(); ok {
		_spec.SetField(resourceaccessgrant.FieldSourceOrderNo, field.TypeString, value)
	}
	if _u.mutation.SourceOrderNoCleared() {
		_spec.ClearField(resourceaccessgrant.FieldSourceOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resourceaccessgrant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(resourceaccessgrant.FieldGrantedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(resourceaccessgrant.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(resourceaccessgrant.FieldExpiredAt, field.TypeTime)
	}
	if _u.mutation.ResourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceaccessgrant.ResourceTable,
			Columns: []string{resourceaccessgrant.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceaccessgrant.ResourceTable,
			Columns: []string{resourceaccessgrant.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResourceItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceaccessgrant.ResourceItemTable,
			Columns: []string{resourceaccessgrant.ResourceItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceaccessgrant.ResourceItemTable,
			Columns: []string{resourceaccessgrant.ResourceItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ResourceAccessGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourceaccessgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
