// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/resource"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceaccessgrant"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceitem"
	"github.com/anzhiyu-c/anheyu-app/ent/resourceorder"
)

// ResourceItemCreate is the builder for creating a ResourceItem entity.
type ResourceItemCreate struct {
	config
	mutation *ResourceItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ResourceItemCreate) SetDeletedAt(v time.Time) *ResourceItemCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ResourceItemCreate) SetNillableDeletedAt(v *time.Time) *ResourceItemCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceItemCreate) SetCreatedAt(v time.Time) *ResourceItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceItemCreate) SetNillableCreatedAt(v *time.Time) *ResourceItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResourceItemCreate) SetUpdatedAt(v time.Time) *ResourceItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResourceItemCreate) SetNillableUpdatedAt(v *time.Time) *ResourceItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *ResourceItemCreate) SetResourceID(v uint) *ResourceItemCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetItemType sets the "item_type" field.
func (_c *ResourceItemCreate) SetItemType(v string) *ResourceItemCreate {
	_c.mutation.SetItemType(v)
	return _c
}

// SetNillableItemType sets the "item_type" field if the given value is not nil.
func (_c *ResourceItemCreate) SetNillableItemType(v *string) *ResourceItemCreate {
	if v != nil {
		_c.SetItemType(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *ResourceItemCreate) SetTitle(v string) *ResourceItemCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *ResourceItemCreate) SetPayload(v map[string]interface{}) *ResourceItemCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResourceItemCreate) SetStatus(v string) *ResourceItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ResourceItemCreate) SetNillableStatus(v *string) *ResourceItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *ResourceItemCreate) SetSort(v int) *ResourceItemCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *ResourceItemCreate) SetNillableSort(v *int) *ResourceItemCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ResourceItemCreate) SetID(v uint) *ResourceItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetResource sets the "resource" edge to the Resource entity.
func (_c *ResourceItemCreate) SetResource(v *Resource) *ResourceItemCreate {
	return _c.SetResourceID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the ResourceOrder entity by IDs.
func (_c *ResourceItemCreate) AddOrderIDs(ids ...uint) *ResourceItemCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the ResourceOrder entity.
func (_c *ResourceItemCreate) AddOrders(v ...*ResourceOrder) *ResourceItemCreate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// AddAccessGrantIDs adds the "access_grants" edge to the ResourceAccessGrant entity by IDs.
func (_c *ResourceItemCreate) AddAccessGrantIDs(ids ...uint) *ResourceItemCreate {
	_c.mutation.AddAccessGrantIDs(ids...)
	return _c
}

// AddAccessGrants adds the "access_grants" edges to the ResourceAccessGrant entity.
func (_c *ResourceItemCreate) AddAccessGrants(v ...*ResourceAccessGrant) *ResourceItemCreate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccessGrantIDs(ids...)
}

// Mutation returns the ResourceItemMutation object of the builder.
func (_c *ResourceItemCreate) Mutation() *ResourceItemMutation {
	return _c.mutation
}

// Save creates the ResourceItem in the database.
func (_c *ResourceItemCreate) Save(ctx context.Context) (*ResourceItem, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceItemCreate) SaveX(ctx context.Context) *ResourceItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceItemCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if resourceitem.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized resourceitem.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := resourceitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if resourceitem.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized resourceitem.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := resourceitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ItemType(); !ok {
		v := resourceitem.DefaultItemType
		_c.mutation.SetItemType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := resourceitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := resourceitem.DefaultSort
		_c.mutation.SetSort(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResourceItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResourceItem.updated_at"`)}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "ResourceItem.resource_id"`)}
	}
	if _, ok := _c.mutation.ItemType(); !ok {
		return &ValidationError{Name: "item_type", err: errors.New(`ent: missing required field "ResourceItem.item_type"`)}
	}
	if v, ok := _c.mutation.ItemType(); ok {
		if err := resourceitem.ItemTypeValidator(v); err != nil {
			return &ValidationError{Name: "item_type", err: fmt.Errorf(`ent: validator failed for field "ResourceItem.item_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ResourceItem.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := resourceitem.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ResourceItem.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ResourceItem.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := resourceitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResourceItem.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "ResourceItem.sort"`)}
	}
	if len(_c.mutation.ResourceIDs()) == 0 {
		return &ValidationError{Name: "resource", err: errors.New(`ent: missing required edge "ResourceItem.resource"`)}
	}
	return nil
}

func (_c *ResourceItemCreate) sqlSave(ctx context.Context) (*ResourceItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceItemCreate) createSpec() (*ResourceItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ResourceItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resourceitem.Table, sqlgraph.NewFieldSpec(resourceitem.FieldID, field.TypeUint))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(resourceitem.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resourceitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resourceitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ItemType(); ok {
		_spec.SetField(resourceitem.FieldItemType, field.TypeString, value)
		_node.ItemType = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(resourceitem.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(resourceitem.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(resourceitem.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(resourceitem.FieldSort, field.TypeInt, value)
		_node.Sort = value
	}
	if nodes := _c.mutation.ResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceitem.ResourceTable,
			Columns: []string{resourceitem.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ResourceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourceitem.OrdersTable,
			Columns: []string{resourceitem.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceorder.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccessGrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourceitem.AccessGrantsTable,
			Columns: []string{resourceitem.AccessGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourceaccessgrant.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceItem.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceItemUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceItemCreate) OnConflict(opts ...sql.ConflictOption) *ResourceItemUpsertOne {
	_c.conflict = opts
	return &ResourceItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceItemCreate) OnConflictColumns(columns ...string) *ResourceItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceItemUpsertOne{
		create: _c,
	}
}

type (
	// ResourceItemUpsertOne is the builder for "upsert"-ing
	//  one ResourceItem node.
	ResourceItemUpsertOne struct {
		create *ResourceItemCreate
	}

	// ResourceItemUpsert is the "OnConflict" setter.
	ResourceItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *ResourceItemUpsert) SetDeletedAt(v time.Time) *ResourceItemUpsert {
	u.Set(resourceitem.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ResourceItemUpsert) UpdateDeletedAt() *ResourceItemUpsert {
	u.SetExcluded(resourceitem.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ResourceItemUpsert) ClearDeletedAt() *ResourceItemUpsert {
	u.SetNull(resourceitem.FieldDeletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceItemUpsert) SetUpdatedAt(v time.Time) *ResourceItemUpsert {
	u.Set(resourceitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceItemUpsert) UpdateUpdatedAt() *ResourceItemUpsert {
	u.SetExcluded(resourceitem.FieldUpdatedAt)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *ResourceItemUpsert) SetResourceID(v uint) *ResourceItemUpsert {
	u.Set(resourceitem.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ResourceItemUpsert) UpdateResourceID() *ResourceItemUpsert {
	u.SetExcluded(resourceitem.FieldResourceID)
	return u
}

// SetItemType sets the "item_type" field.
func (u *ResourceItemUpsert) SetItemType(v string) *ResourceItemUpsert {
	u.Set(resourceitem.FieldItemType, v)
	return u
}

// UpdateItemType sets the "item_type" field to the value that was provided on create.
func (u *ResourceItemUpsert) UpdateItemType() *ResourceItemUpsert {
	u.SetExcluded(resourceitem.FieldItemType)
	return u
}

// SetTitle sets the "title" field.
func (u *ResourceItemUpsert) SetTitle(v string) *ResourceItemUpsert {
	u.Set(resourceitem.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ResourceItemUpsert) UpdateTitle() *ResourceItemUpsert {
	u.SetExcluded(resourceitem.FieldTitle)
	return u
}

// SetPayload sets the "payload" field.
func (u *ResourceItemUpsert) SetPayload(v map[string]interface{}) *ResourceItemUpsert {
	u.Set(resourceitem.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ResourceItemUpsert) UpdatePayload() *ResourceItemUpsert {
	u.SetExcluded(resourceitem.FieldPayload)
	return u
}

// ClearPayload clears the value of the "payload" field.
func (u *ResourceItemUpsert) ClearPayload() *ResourceItemUpsert {
	u.SetNull(resourceitem.FieldPayload)
	return u
}

// SetStatus sets the "status" field.
func (u *ResourceItemUpsert) SetStatus(v string) *ResourceItemUpsert {
	u.Set(resourceitem.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResourceItemUpsert) UpdateStatus() *ResourceItemUpsert {
	u.SetExcluded(resourceitem.FieldStatus)
	return u
}

// SetSort sets the "sort" field.
func (u *ResourceItemUpsert) SetSort(v int) *ResourceItemUpsert {
	u.Set(resourceitem.FieldSort, v)
	return u
}

// UpdateSort sets the "sort" field to the value that was provided on create.
func (u *ResourceItemUpsert) UpdateSort() *ResourceItemUpsert {
	u.SetExcluded(resourceitem.FieldSort)
	return u
}

// AddSort adds v to the "sort" field.
func (u *ResourceItemUpsert) AddSort(v int) *ResourceItemUpsert {
	u.Add(resourceitem.FieldSort, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ResourceItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resourceitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResourceItemUpsertOne) UpdateNewValues() *ResourceItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(resourceitem.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resourceitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResourceItemUpsertOne) Ignore() *ResourceItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceItemUpsertOne) DoNothing() *ResourceItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceItemCreate.OnConflict
// documentation for more info.
func (u *ResourceItemUpsertOne) Update(set func(*ResourceItemUpsert)) *ResourceItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ResourceItemUpsertOne) SetDeletedAt(v time.Time) *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ResourceItemUpsertOne) UpdateDeletedAt() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ResourceItemUpsertOne) ClearDeletedAt() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceItemUpsertOne) SetUpdatedAt(v time.Time) *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceItemUpsertOne) UpdateUpdatedAt() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *ResourceItemUpsertOne) SetResourceID(v uint) *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ResourceItemUpsertOne) UpdateResourceID() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateResourceID()
	})
}

// SetItemType sets the "item_type" field.
func (u *ResourceItemUpsertOne) SetItemType(v string) *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetItemType(v)
	})
}

// UpdateItemType sets the "item_type" field to the value that was provided on create.
func (u *ResourceItemUpsertOne) UpdateItemType() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateItemType()
	})
}

// SetTitle sets the "title" field.
func (u *ResourceItemUpsertOne) SetTitle(v string) *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ResourceItemUpsertOne) UpdateTitle() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateTitle()
	})
}

// SetPayload sets the "payload" field.
func (u *ResourceItemUpsertOne) SetPayload(v map[string]interface{}) *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ResourceItemUpsertOne) UpdatePayload() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *ResourceItemUpsertOne) ClearPayload() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.ClearPayload()
	})
}

// SetStatus sets the "status" field.
func (u *ResourceItemUpsertOne) SetStatus(v string) *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResourceItemUpsertOne) UpdateStatus() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateStatus()
	})
}

// SetSort sets the "sort" field.
func (u *ResourceItemUpsertOne) SetSort(v int) *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetSort(v)
	})
}

// AddSort adds v to the "sort" field.
func (u *ResourceItemUpsertOne) AddSort(v int) *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.AddSort(v)
	})
}

// UpdateSort sets the "sort" field to the value that was provided on create.
func (u *ResourceItemUpsertOne) UpdateSort() *ResourceItemUpsertOne {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateSort()
	})
}

// Exec executes the query.
func (u *ResourceItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResourceItemUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResourceItemUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResourceItemCreateBulk is the builder for creating many ResourceItem entities in bulk.
type ResourceItemCreateBulk struct {
	config
	err      error
	builders []*ResourceItemCreate
	conflict []sql.ConflictOption
}

// Save creates the ResourceItem entities in the database.
func (_c *ResourceItemCreateBulk) Save(ctx context.Context) ([]*ResourceItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResourceItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceItemCreateBulk) SaveX(ctx context.Context) []*ResourceItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceItemUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResourceItemUpsertBulk {
	_c.conflict = opts
	return &ResourceItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceItemCreateBulk) OnConflictColumns(columns ...string) *ResourceItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceItemUpsertBulk{
		create: _c,
	}
}

// ResourceItemUpsertBulk is the builder for "upsert"-ing
// a bulk of ResourceItem nodes.
type ResourceItemUpsertBulk struct {
	create *ResourceItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResourceItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resourceitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResourceItemUpsertBulk) UpdateNewValues() *ResourceItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(resourceitem.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resourceitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResourceItemUpsertBulk) Ignore() *ResourceItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceItemUpsertBulk) DoNothing() *ResourceItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceItemCreateBulk.OnConflict
// documentation for more info.
func (u *ResourceItemUpsertBulk) Update(set func(*ResourceItemUpsert)) *ResourceItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ResourceItemUpsertBulk) SetDeletedAt(v time.Time) *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ResourceItemUpsertBulk) UpdateDeletedAt() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ResourceItemUpsertBulk) ClearDeletedAt() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceItemUpsertBulk) SetUpdatedAt(v time.Time) *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceItemUpsertBulk) UpdateUpdatedAt() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *ResourceItemUpsertBulk) SetResourceID(v uint) *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ResourceItemUpsertBulk) UpdateResourceID() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateResourceID()
	})
}

// SetItemType sets the "item_type" field.
func (u *ResourceItemUpsertBulk) SetItemType(v string) *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetItemType(v)
	})
}

// UpdateItemType sets the "item_type" field to the value that was provided on create.
func (u *ResourceItemUpsertBulk) UpdateItemType() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateItemType()
	})
}

// SetTitle sets the "title" field.
func (u *ResourceItemUpsertBulk) SetTitle(v string) *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ResourceItemUpsertBulk) UpdateTitle() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateTitle()
	})
}

// SetPayload sets the "payload" field.
func (u *ResourceItemUpsertBulk) SetPayload(v map[string]interface{}) *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ResourceItemUpsertBulk) UpdatePayload() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *ResourceItemUpsertBulk) ClearPayload() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.ClearPayload()
	})
}

// SetStatus sets the "status" field.
func (u *ResourceItemUpsertBulk) SetStatus(v string) *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResourceItemUpsertBulk) UpdateStatus() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateStatus()
	})
}

// SetSort sets the "sort" field.
func (u *ResourceItemUpsertBulk) SetSort(v int) *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.SetSort(v)
	})
}

// AddSort adds v to the "sort" field.
func (u *ResourceItemUpsertBulk) AddSort(v int) *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.AddSort(v)
	})
}

// UpdateSort sets the "sort" field to the value that was provided on create.
func (u *ResourceItemUpsertBulk) UpdateSort() *ResourceItemUpsertBulk {
	return u.Update(func(s *ResourceItemUpsert) {
		s.UpdateSort()
	})
}

// Exec executes the query.
func (u *ResourceItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResourceItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
