// Code generated by ent, DO NOT EDIT.

package resource

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the resource type in the database.
	Label = "resource"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldHostType holds the string denoting the host_type field in the database.
	FieldHostType = "host_type"
	// FieldHostID holds the string denoting the host_id field in the database.
	FieldHostID = "host_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldCoverURL holds the string denoting the cover_url field in the database.
	FieldCoverURL = "cover_url"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSaleEnabled holds the string denoting the sale_enabled field in the database.
	FieldSaleEnabled = "sale_enabled"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldOriginalPrice holds the string denoting the original_price field in the database.
	FieldOriginalPrice = "original_price"
	// FieldMemberFree holds the string denoting the member_free field in the database.
	FieldMemberFree = "member_free"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// EdgeItems holds the string denoting the items edge name in mutations.
	EdgeItems = "items"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// EdgeAccessGrants holds the string denoting the access_grants edge name in mutations.
	EdgeAccessGrants = "access_grants"
	// Table holds the table name of the resource in the database.
	Table = "resources"
	// ItemsTable is the table that holds the items relation/edge.
	ItemsTable = "resource_items"
	// ItemsInverseTable is the table name for the ResourceItem entity.
	// It exists in this package in order to avoid circular dependency with the "resourceitem" package.
	ItemsInverseTable = "resource_items"
	// ItemsColumn is the table column denoting the items relation/edge.
	ItemsColumn = "resource_id"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "resource_orders"
	// OrdersInverseTable is the table name for the ResourceOrder entity.
	// It exists in this package in order to avoid circular dependency with the "resourceorder" package.
	OrdersInverseTable = "resource_orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "resource_id"
	// AccessGrantsTable is the table that holds the access_grants relation/edge.
	AccessGrantsTable = "resource_access_grants"
	// AccessGrantsInverseTable is the table name for the ResourceAccessGrant entity.
	// It exists in this package in order to avoid circular dependency with the "resourceaccessgrant" package.
	AccessGrantsInverseTable = "resource_access_grants"
	// AccessGrantsColumn is the table column denoting the access_grants relation/edge.
	AccessGrantsColumn = "resource_id"
)

// Columns holds all SQL columns for resource fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldHostType,
	FieldHostID,
	FieldTitle,
	FieldSummary,
	FieldCoverURL,
	FieldResourceType,
	FieldStatus,
	FieldSaleEnabled,
	FieldPrice,
	FieldOriginalPrice,
	FieldMemberFree,
	FieldSort,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/anzhiyu-c/anheyu-app/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// HostTypeValidator is a validator for the "host_type" field. It is called by the builders before save.
	HostTypeValidator func(string) error
	// HostIDValidator is a validator for the "host_id" field. It is called by the builders before save.
	HostIDValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	SummaryValidator func(string) error
	// CoverURLValidator is a validator for the "cover_url" field. It is called by the builders before save.
	CoverURLValidator func(string) error
	// DefaultResourceType holds the default value on creation for the "resource_type" field.
	DefaultResourceType string
	// ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	ResourceTypeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSaleEnabled holds the default value on creation for the "sale_enabled" field.
	DefaultSaleEnabled bool
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultOriginalPrice holds the default value on creation for the "original_price" field.
	DefaultOriginalPrice float64
	// DefaultMemberFree holds the default value on creation for the "member_free" field.
	DefaultMemberFree bool
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort int
)

// OrderOption defines the ordering options for the Resource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByHostType orders the results by the host_type field.
func ByHostType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostType, opts...).ToFunc()
}

// ByHostID orders the results by the host_id field.
func ByHostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByCoverURL orders the results by the cover_url field.
func ByCoverURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverURL, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySaleEnabled orders the results by the sale_enabled field.
func BySaleEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSaleEnabled, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByOriginalPrice orders the results by the original_price field.
func ByOriginalPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalPrice, opts...).ToFunc()
}

// ByMemberFree orders the results by the member_free field.
func ByMemberFree(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberFree, opts...).ToFunc()
}

// BySort orders the results by the sort field.
func BySort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSort, opts...).ToFunc()
}

// ByItemsCount orders the results by items count.
func ByItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newItemsStep(), opts...)
	}
}

// ByItems orders the results by items terms.
func ByItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOrdersCount orders the results by orders count.
func ByOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrdersStep(), opts...)
	}
}

// ByOrders orders the results by orders terms.
func ByOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAccessGrantsCount orders the results by access_grants count.
func ByAccessGrantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccessGrantsStep(), opts...)
	}
}

// ByAccessGrants orders the results by access_grants terms.
func ByAccessGrants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccessGrantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
	)
}
func newOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
	)
}
func newAccessGrantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccessGrantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AccessGrantsTable, AccessGrantsColumn),
	)
}
